DROP TABLE abbrevconsolidado;
CREATE TABLE abbrevconsolidado AS
SELECT isolabel_ext, layer, field, abbrev, nabrrev
FROM
(
VALUES
('BR-MG-Contagem','via',1,'ALA','Alameda'),
('BR-MG-Contagem','via',1,'Av.','Avenida'),
('BR-MG-Contagem','via',1,'Bec','Beco'),
('BR-MG-Contagem','via',1,'Est.','Estrada'),
('BR-MG-Contagem','via',1,'Pca.','Praça'),
('BR-MG-Contagem','via',1,'Pça.','Praça'),
('BR-MG-Contagem','via',1,'R\ua','Rua'),
('BR-MG-Contagem','via',1,'Rod.','Rodovia'),
('BR-MG-Contagem','via',1,'Trv','Travessa'),
('BR-MG-Contagem','via',1,'Trv.','Travessa'),
('BR-MG-Contagem','via',1,'Tvr.','Travessa'),
('BR-MG-Contagem','via',6,'Sra.','Senhora'),
('BR-MG-Contagem','via',2,'BEM-TE-VI','Bem-te-vi'),
-- ('BR-MG-Contagem','via',1,'S.JOSE',''),

('BR-MG-Contagem','geoaddress',1,'Ala','Alameda'),
('BR-MG-Contagem','geoaddress',1,'Av.','Avenida'),
('BR-MG-Contagem','geoaddress',1,'Bec','Beco'),
('BR-MG-Contagem','geoaddress',1,'Est.','Estrada'),
('BR-MG-Contagem','geoaddress',1,'Pca','Praça'),
('BR-MG-Contagem','geoaddress',1,'Rod.','Rodovia'),
('BR-MG-Contagem','geoaddress',1,'Trv','Travessa'),
('BR-MG-Contagem','geoaddress',2,'1.','1'),
('BR-MG-Contagem','geoaddress',2,'CAP.','Capitão'),
('BR-MG-Contagem','geoaddress',2,'CEL','Coronel'),
('BR-MG-Contagem','geoaddress',2,'CEL.','Coronel'),
('BR-MG-Contagem','geoaddress',2,'GAL','General'),
('BR-MG-Contagem','geoaddress',2,'GAL.','General'),
('BR-MG-Contagem','geoaddress',2,'DR','Doutor'),
('BR-MG-Contagem','geoaddress',2,'DR.','Doutor'),
('BR-MG-Contagem','geoaddress',2,'Dr','Doutor'),
('BR-MG-Contagem','geoaddress',2,'ESP.','Expedicionário'),
('BR-MG-Contagem','geoaddress',2,'PROF.','Professor'),
('BR-MG-Contagem','geoaddress',2,'SARG.','Sargento'),
('BR-MG-Contagem','geoaddress',3,'(Cj','(Conjunto'),
('BR-MG-Contagem','geoaddress',2,'VER.','Vereador'),
('BR-MG-Contagem','geoaddress',2,'DEP.','Deputado'),
('BR-MG-Contagem','geoaddress',2,'DES.','Desembargador'),
('BR-MG-Contagem','geoaddress',3,'(THEREZINHA','(Therezinha'),
('BR-MG-Contagem','geoaddress',5,'"A"','A'),
('BR-MG-Contagem','geoaddress',4,'D''AVIL','D''Ávila'),
('BR-MG-Contagem','geoaddress',4,'DAVILA','D''Ávila'),
('BR-MG-Contagem','geoaddress',3,'D.AGUA','D''Água'),
('BR-MG-Contagem','geoaddress',3,'A.PASCOALINE','Alberto Pascoaline'),
('BR-MG-Contagem','geoaddress',3,'Ant.Guido','Antônio Guido'),
('BR-MG-Contagem','geoaddress',2,'B.H.','Belo Horizonte'),
('BR-MG-Contagem','geoaddress',2,'1.DE','1 DE'),
('BR-MG-Contagem','geoaddress',2,'CEL.AMERICO','CORONEL AMERICO'),
('BR-MG-Contagem','geoaddress',2,'CEL.ANTONIO','CORONEL ANTONIO'),
('BR-MG-Contagem','geoaddress',2,'CEL.ATILA','CORONEL ATILA'),
('BR-MG-Contagem','geoaddress',2,'CEL.BELMIRO','CORONEL BELMIRO'),
('BR-MG-Contagem','geoaddress',2,'CEL.BENJAMIM','CORONEL BENJAMIM'),
('BR-MG-Contagem','geoaddress',2,'CEL.DOUCHA','CORONEL DOUCHA'),
('BR-MG-Contagem','geoaddress',2,'CEL.DURVAL','CORONEL DURVAL'),
('BR-MG-Contagem','geoaddress',2,'CEL.ERASMO','CORONEL ERASMO'),
('BR-MG-Contagem','geoaddress',2,'CEL.FELICIANO','CORONEL FELICIANO'),
('BR-MG-Contagem','geoaddress',2,'CEL.FRANCISCO','CORONEL FRANCISCO'),
('BR-MG-Contagem','geoaddress',2,'CEL.GABRIEL','CORONEL GABRIEL'),
('BR-MG-Contagem','geoaddress',2,'CEL.GALDINO','CORONEL GALDINO'),
('BR-MG-Contagem','geoaddress',2,'CEL.GODOFREDO','CORONEL GODOFREDO'),
('BR-MG-Contagem','geoaddress',2,'CEL.JOAO','CORONEL JOAO'),
('BR-MG-Contagem','geoaddress',2,'CEL.JOAQUIM','CORONEL JOAQUIM'),
('BR-MG-Contagem','geoaddress',2,'CEL.JOSE','CORONEL JOSE'),
('BR-MG-Contagem','geoaddress',2,'CEL.JOVE','CORONEL JOVE'),
('BR-MG-Contagem','geoaddress',2,'CEL.JOVIANO','CORONEL JOVIANO'),
('BR-MG-Contagem','geoaddress',2,'CEL.LAURO','CORONEL LAURO'),
('BR-MG-Contagem','geoaddress',2,'CEL.MANOEL','CORONEL MANOEL'),
('BR-MG-Contagem','geoaddress',2,'CEL.MARCONDES','CORONEL MARCONDES'),
('BR-MG-Contagem','geoaddress',2,'CEL.MARIO','CORONEL MARIO'),
('BR-MG-Contagem','geoaddress',2,'CEL.MURTA','CORONEL MURTA'),
('BR-MG-Contagem','geoaddress',2,'CEL.ODILON','CORONEL ODILON'),
('BR-MG-Contagem','geoaddress',2,'CEL.OLEGARIO','CORONEL OLEGARIO'),
('BR-MG-Contagem','geoaddress',2,'CEL.SALVADOR','CORONEL SALVADOR'),
('BR-MG-Contagem','geoaddress',2,'CEL.SILVESTRE','CORONEL SILVESTRE'),
('BR-MG-Contagem','geoaddress',2,'CEL.VICENTE','CORONEL VICENTE'),
('BR-MG-Contagem','geoaddress',2,'CEL.WALDIVINO','CORONEL WALDIVINO'),
('BR-MG-Contagem','geoaddress',2,'DEP.LOURENCO','DEPUTADO LOURENCO'),
('BR-MG-Contagem','geoaddress',2,'DES.LUCIANO','DESEMBARGADOR LUCIANO'),
('BR-MG-Contagem','geoaddress',2,'GAL.DAVID','GENERAL DAVID'),
('BR-MG-Contagem','geoaddress',2,'GAL.ZENOBIO','GENERAL ZENOBIO'),
('BR-MG-Contagem','geoaddress',2,'PROF.ALFREDO','PROFESSOR ALFREDO'),
('BR-MG-Contagem','geoaddress',2,'PROF.ALVES','PROFESSOR ALVES'),
('BR-MG-Contagem','geoaddress',2,'PROF.AURELIANO','PROFESSOR AURELIANO'),
('BR-MG-Contagem','geoaddress',2,'PROF.CICERO','PROFESSOR CICERO'),
('BR-MG-Contagem','geoaddress',2,'PROF.CICERO','PROFESSOR CICERO'),
('BR-MG-Contagem','geoaddress',2,'PROF.FILOMENA','PROFESSORA FILOMENA'),
('BR-MG-Contagem','geoaddress',2,'PROF.JOSE','PROFESSOR JOSE'),
('BR-MG-Contagem','geoaddress',2,'PROF.JOSEFINA','PROFESSORA JOSEFINA'),
('BR-MG-Contagem','geoaddress',2,'PROF.MELO','PROFESSOR MELO'),
('BR-MG-Contagem','geoaddress',2,'PROF.NEUZA','PROFESSORA NEUZA'),
('BR-MG-Contagem','geoaddress',2,'PROF.PEDRO','PROFESSOR PEDRO'),
('BR-MG-Contagem','geoaddress',2,'PROF.PINHEIRO','PROFESSOR PINHEIRO'),
('BR-MG-Contagem','geoaddress',2,'PROF.PINTO','PROFESSOR PINTO'),
('BR-MG-Contagem','geoaddress',2,'PROF.RUBENS','PROFESSOR RUBENS'),
('BR-MG-Contagem','geoaddress',2,'PROF.SANTIAGO','PROFESSOR SANTIAGO'),
('BR-MG-Contagem','geoaddress',2,'PROF.SIGEFREDO','PROFESSOR SIGEFREDO'),
('BR-MG-Contagem','geoaddress',2,'SARG.ZACARIAS','SARGENTO ZACARIAS'),

('BR-MG-Contagem','parcel',1,'CONJ.','Conjunto'),
('BR-MG-Contagem','parcel',2,'HAB.','Habitacional'),
('BR-MG-Contagem','parcel',3,'VER.','Vereador'),
('BR-SP-Jundiai','geoaddress',1,'AL','Alameda'),
('BR-SP-Jundiai','geoaddress',1,'AV','Avenida'),
-- ('BR-SP-Jundiai','geoaddress',1,'CM',''),
('BR-SP-Jundiai','geoaddress',1,'ET','Estrada'),
('BR-SP-Jundiai','geoaddress',1,'PC','Praça'),
('BR-SP-Jundiai','geoaddress',1,'R','Rua'),
('BR-SP-Jundiai','geoaddress',1,'RD','Rodovia'),
('BR-SP-Jundiai','geoaddress',1,'TV','Travessa'),
('BR-SP-Jundiai','geoaddress',1,'V','Via'),
('BR-SP-Jundiai','geoaddress',1,'VD','Viaduto'),
('BR-SP-Jundiai','geoaddress',1,'VL','Vila'),
-- ('BR-SP-Jundiai','geoaddress',1,'VP',''),
('BR-SP-Jundiai','geoaddress',2,'DR','Doutor'),
('BR-SP-Jundiai','geoaddress',2,'PRFA','Professora'),
('BR-SP-Jundiai','geoaddress',2,'PROF','Professor'),
('BR-SP-Jundiai','geoaddress',2,'PREB','Presbítero'),
('BR-SP-Jundiai','geoaddress',2,'PROLONG','Prolongamento'),
('BR-SP-Jundiai','geoaddress',2,'STA','Santa'),
('BR-SP-Jundiai','geoaddress',2,'SOR','Soror'),
('BR-SP-Jundiai','geoaddress',2,'VER','Vereador'),
('BR-SP-Jundiai','geoaddress',2,'CAP','Capitão'),
('BR-SP-Jundiai','geoaddress',2,'CB','Cabo'),
('BR-SP-Jundiai','geoaddress',2,'CDE','Conde'),
('BR-SP-Jundiai','geoaddress',2,'CDOR','Comendador'),
('BR-SP-Jundiai','geoaddress',2,'CEL','Coronel'),
('BR-SP-Jundiai','geoaddress',2,'DIAC','Diácomo'),
('BR-SP-Jundiai','geoaddress',2,'DRA','Doutora'),
('BR-SP-Jundiai','geoaddress',2,'ENG','Engenheiro'),
('BR-SP-Jundiai','geoaddress',2,'EVA','Evangelista'),
('BR-SP-Jundiai','geoaddress',2,'FR','Frei'),
('BR-SP-Jundiai','geoaddress',2,'GEN','General'),
('BR-SP-Jundiai','geoaddress',2,'MAJ','Major'),
('BR-SP-Jundiai','geoaddress',2,'MI','Missionário'),
('BR-SP-Jundiai','geoaddress',2,'MIN','Ministro'),
('BR-SP-Jundiai','geoaddress',2,'MON','Monsenhor'),
('BR-SP-Jundiai','geoaddress',2,'MTRO','Maestro'),
('BR-SP-Jundiai','geoaddress',2,'PA','Pastor'),
('BR-SP-Jundiai','geoaddress',2,'PE','Padre'),
('BR-SP-Jundiai','geoaddress',2,'PRSA','Princesa'),
('BR-SP-Jundiai','geoaddress',2,'S/DENOMINAÇÃO','Sem denominação'),
('BR-SP-Jundiai','geoaddress',2,'SGT','Sargento'),
('BR-SP-Jundiai','geoaddress',2,'STA','Santa'),
('BR-SP-Jundiai','geoaddress',2,'STO','Santo'),
('BR-SP-Jundiai','geoaddress',2,'TEN','Tenente'),
('BR-SP-Jundiai','geoaddress',2,'VER','Vereador'),
('BR-SP-Jundiai','geoaddress',2,'VIG','Vigário'),
('BR-SP-Jundiai','geoaddress',2,'VISC','Visconde'),
('BR-SP-Jundiai','geoaddress',2,'PRES','Presidente'),
('BR-SP-Jundiai','geoaddress',2,'CMTE','Comandante'),

('BR-SP-Jundiai','geoaddress',2,'BRANCA/S.INDUS.','Branca/Setor Industrial'),
('BR-SP-Jundiai','geoaddress',1,'JD','Jardim'),
('BR-SP-Jundiai','geoaddress',1,'JD.SANTA','Jardim Santa'),

('BR-SP-Jundiai','via',1,'AC','Acesso'),
('BR-SP-Jundiai','via',1,'AL','Alameda'),
('BR-SP-Jundiai','via',1,'AV','Avenida'),
-- ('BR-SP-Jundiai','via',1,'CM',''),
('BR-SP-Jundiai','via',1,'ET','Estrada'),
('BR-SP-Jundiai','via',1,'PC','Praça'),
-- ('BR-SP-Jundiai','via',1,'PL',''),
('BR-SP-Jundiai','via',1,'PT','Ponte'),
('BR-SP-Jundiai','via',1,'R','Rua'),
('BR-SP-Jundiai','via',1,'RD','Rodovia'),
('BR-SP-Jundiai','via',1,'TU','Túnel'),
('BR-SP-Jundiai','via',1,'TV','Travessa'),
('BR-SP-Jundiai','via',1,'V','Via'),
('BR-SP-Jundiai','via',1,'VD','Viaduto'),
('BR-SP-Jundiai','via',1,'VL','Vila'),
-- ('BR-SP-Jundiai','via',1,'VP',''),

('BR-SP-Jundiai','via',2,'CAP','Capitão'),
('BR-SP-Jundiai','via',2,'CB','Cabo'),
('BR-SP-Jundiai','via',2,'CDE','Conde'),
('BR-SP-Jundiai','via',2,'CDOR','Comendador'),
('BR-SP-Jundiai','via',2,'CEL','Coronel'),
('BR-SP-Jundiai','via',2,'CMTE','Comandante'),
('BR-SP-Jundiai','via',2,'DIAC','Diácomo'),
('BR-SP-Jundiai','via',2,'DR','Doutor'),
('BR-SP-Jundiai','via',2,'DRA','Doutora'),
('BR-SP-Jundiai','via',2,'ENG','Engenheiro'),
('BR-SP-Jundiai','via',2,'EVA','Evangelista'),
('BR-SP-Jundiai','via',2,'FR','Frei'),
('BR-SP-Jundiai','via',2,'GEN','General'),
('BR-SP-Jundiai','via',2,'MAJ','Major'),
('BR-SP-Jundiai','via',2,'MAL','Marechal'),
('BR-SP-Jundiai','via',2,'MI','Missionário'),
('BR-SP-Jundiai','via',2,'MIN','Ministro'),
('BR-SP-Jundiai','via',2,'MON','Monsenhor'),
('BR-SP-Jundiai','via',2,'MONS','Monsenhor'),
('BR-SP-Jundiai','via',2,'MQ','Marquês'),
('BR-SP-Jundiai','via',2,'MTRO','Maestro'),
('BR-SP-Jundiai','via',2,'PA','Pastor'),
('BR-SP-Jundiai','via',2,'PE','Padre'),
('BR-SP-Jundiai','via',2,'PM','Policial Militar'),
('BR-SP-Jundiai','via',2,'PREB','Presbítero'),
('BR-SP-Jundiai','via',2,'PRES','Presidente'),
('BR-SP-Jundiai','via',2,'PRFA','Professora'),
('BR-SP-Jundiai','via',2,'PROF','Professor'),
('BR-SP-Jundiai','via',2,'PREF','Prefeito'),
('BR-SP-Jundiai','via',2,'PROLONG','Prolongamento'),
('BR-SP-Jundiai','via',2,'PRSA','Princesa'),
('BR-SP-Jundiai','via',2,'S/DENOMINAÇÃO','Sem denominação'),
('BR-SP-Jundiai','via',2,'SEN','Senador'),
('BR-SP-Jundiai','via',2,'SGT','Sargento'),
('BR-SP-Jundiai','via',2,'SOR','Soror'),
('BR-SP-Jundiai','via',2,'STA','Santa'),
('BR-SP-Jundiai','via',2,'STA','Santa'),
('BR-SP-Jundiai','via',2,'STO','Santo'),
('BR-SP-Jundiai','via',2,'TEN','Tenente'),
('BR-SP-Jundiai','via',2,'VER','Vereador'),
('BR-SP-Jundiai','via',2,'VER','Vereador'),
('BR-SP-Jundiai','via',2,'VIG','Vigário'),
('BR-SP-Jundiai','via',2,'VISC','Visconde'),
('BR-SP-Jundiai','via',2,'PART','Particular'),
('BR-SP-Jundiai','via',2,'PROJ','Projetada'),

('BR-SP-Jundiai','via',3,'JD','Jardim'),
('BR-SP-Jundiai','via',3,'(Jd','(Jardim'),
('BR-SP-Jundiai','via',3,'LT.','Loteamento'),
('BR-SP-Jundiai','via',3,'RES','Residencial'),
('BR-SP-Jundiai','via',3,'R','Rua'),

('BR-CE-Fortaleza','parcel',2,'ALMIRANTEBARROSO','ALMIRANTE BARROSO'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTEHENRIQUE','ALMIRANTE HENRIQUE'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTEJACEGUAI','ALMIRANTE JACEGUAI'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTEMAXIMIANO','ALMIRANTE MAXIMIANO'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTERUBIM','ALMIRANTE RUBIM'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTERUFINO','ALMIRANTE RUFINO'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTESOARES','ALMIRANTE SOARES'),
('BR-CE-Fortaleza','parcel',2,'ALMIRANTETAMANDARÉ','ALMIRANTE TAMANDARÉ'),
('BR-CE-Fortaleza','parcel',2,'ARQUITETOEMÍLIO','ARQUITETO EMÍLIO'),
('BR-CE-Fortaleza','parcel',2,'ARQUITETOJOÃO','ARQUITETO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'ARQUITETOREGINALDO','ARQUITETO REGINALDO'),
('BR-CE-Fortaleza','parcel',2,'ASPIRANTEMENDES','ASPIRANTE MENDES'),
('BR-CE-Fortaleza','parcel',2,'BARAOAQUIRAZ','BARAO AQUIRAZ'),
('BR-CE-Fortaleza','parcel',2,'BARAOCANINDE','BARAO CANINDE'),
('BR-CE-Fortaleza','parcel',2,'BARAODE','BARAO DE'),
('BR-CE-Fortaleza','parcel',2,'BARAODO','BARAO DO'),
('BR-CE-Fortaleza','parcel',2,'BARAOSANTO','BARAO SANTO'),
('BR-CE-Fortaleza','parcel',2,'BARAOVASCONCELOS','BARAO VASCONCELOS'),
('BR-CE-Fortaleza','parcel',2,'BRIGADEIROCORREIA','BRIGADEIRO CORREIA'),
('BR-CE-Fortaleza','parcel',2,'BRIGADEIROHAROLDO','BRIGADEIRO HAROLDO'),
('BR-CE-Fortaleza','parcel',2,'BRIGADEIROTORRES','BRIGADEIRO TORRES'),
('BR-CE-Fortaleza','parcel',2,'BRIGADEIROVILELA','BRIGADEIRO VILELA'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOAFRANIO','CAPITAO AFRANIO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOAFRÂNIO','CAPITAO AFRÂNIO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOAMERICO','CAPITAO AMERICO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOANTONIO','CAPITAO ANTONIO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOARAGAO','CAPITAO ARAGAO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOARAGÃO','CAPITAO ARAGÃO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOAVIADOR','CAPITAO AVIADOR'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOBRASIL','CAPITAO BRASIL'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOCLÓVIS','CAPITAO CLÓVIS'),
('BR-CE-Fortaleza','parcel',2,'CAPITAODAKIR','CAPITAO DAKIR'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOGUSTAVO','CAPITAO GUSTAVO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOGUTEMBERG','CAPITAO GUTEMBERG'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOHERMÍNIO','CAPITAO HERMÍNIO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOHUGO','CAPITAO HUGO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOISRAEL','CAPITAO ISRAEL'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOJOSÉ','CAPITAO JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOJOÃO','CAPITAO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOJUSTINO','CAPITAO JUSTINO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOMELO','CAPITAO MELO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAONESTOR','CAPITAO NESTOR'),
('BR-CE-Fortaleza','parcel',2,'CAPITAONOGUEIRA','CAPITAO NOGUEIRA'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOOLAVO','CAPITAO OLAVO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOPINTO','CAPITAO PINTO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOPORFÍRIO','CAPITAO PORFÍRIO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOSAMPAIO','CAPITAO SAMPAIO'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOSANTOS','CAPITAO SANTOS'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOTHEOGENES','CAPITAO THEOGENES'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOURUGUAI','CAPITAO URUGUAI'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOVASCONCELOS','CAPITAO VASCONCELOS'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOWALDEMAR','CAPITAO WALDEMAR'),
('BR-CE-Fortaleza','parcel',2,'CAPITAOXIMENES','CAPITAO XIMENES'),
('BR-CE-Fortaleza','parcel',2,'CARDEALALBINO','CARDEAL ALBINO'),
('BR-CE-Fortaleza','parcel',2,'CARDEALARCOVERDE','CARDEAL ARCOVERDE'),
('BR-CE-Fortaleza','parcel',2,'COLETORANTÔNIO','COLETOR ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'COMANDANTEHAROLDO','COMANDANTE HAROLDO'),
('BR-CE-Fortaleza','parcel',2,'COMANDANTEJOSÉ','COMANDANTE JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'COMANDANTEPRATA','COMANDANTE PRATA'),
('BR-CE-Fortaleza','parcel',2,'COMANDANTERIPPER','COMANDANTE RIPPER'),
('BR-CE-Fortaleza','parcel',2,'COMENDADORACIOLY','COMENDADOR ACIOLY'),
('BR-CE-Fortaleza','parcel',2,'COMENDADORFRANCISCO','COMENDADOR FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'COMENDADORGARCIA','COMENDADOR GARCIA'),
('BR-CE-Fortaleza','parcel',2,'COMENDADORJOSE','COMENDADOR JOSE'),
('BR-CE-Fortaleza','parcel',2,'COMENDADORLUIS','COMENDADOR LUIS'),
('BR-CE-Fortaleza','parcel',2,'COMENDADORMACHADO','COMENDADOR MACHADO'),
('BR-CE-Fortaleza','parcel',2,'COMERCIANTEASSIS','COMERCIANTE ASSIS'),
('BR-CE-Fortaleza','parcel',2,'CONDED''EU','CONDE D''EU'),
('BR-CE-Fortaleza','parcel',2,'CONDEJANUÁRIO','CONDE JANUÁRIO'),
('BR-CE-Fortaleza','parcel',2,'CONEGOBESSA','CONEGO BESSA'),
('BR-CE-Fortaleza','parcel',2,'CONEGOBRAVEZA','CONEGO BRAVEZA'),
('BR-CE-Fortaleza','parcel',2,'CONEGODE','CONEGO DE'),
('BR-CE-Fortaleza','parcel',2,'CONEGOLIMA','CONEGO LIMA'),
('BR-CE-Fortaleza','parcel',2,'CONEGOMOURÃO','CONEGO MOURÃO'),
('BR-CE-Fortaleza','parcel',2,'CONEGOPENNAFORT','CONEGO PENNAFORT'),
('BR-CE-Fortaleza','parcel',2,'CONEGOPINTO','CONEGO PINTO'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROARAÚJO','CONSELHEIRO ARAÚJO'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROESTELITA','CONSELHEIRO ESTELITA'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROGALVÃO','CONSELHEIRO GALVÃO'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROGOMES','CONSELHEIRO GOMES'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROLAFAYETTE','CONSELHEIRO LAFAYETTE'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROQUINDERÉ','CONSELHEIRO QUINDERÉ'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROSILVA','CONSELHEIRO SILVA'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROTRISTÃO','CONSELHEIRO TRISTÃO'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROVIEIRA','CONSELHEIRO VIEIRA'),
('BR-CE-Fortaleza','parcel',2,'CONSELHEIROÁLVARO','CONSELHEIRO ÁLVARO'),
('BR-CE-Fortaleza','parcel',2,'CORONELABELARDO','CORONEL ABELARDO'),
('BR-CE-Fortaleza','parcel',2,'CORONELALEXANDRINO','CORONEL ALEXANDRINO'),
('BR-CE-Fortaleza','parcel',2,'CORONELALUISIO','CORONEL ALUISIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELALVES','CORONEL ALVES'),
('BR-CE-Fortaleza','parcel',2,'CORONELALÍPIO','CORONEL ALÍPIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELAMANCIO','CORONEL AMANCIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELANTÔNIO','CORONEL ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELARGEMIRO','CORONEL ARGEMIRO'),
('BR-CE-Fortaleza','parcel',2,'CORONELBELO','CORONEL BELO'),
('BR-CE-Fortaleza','parcel',2,'CORONELCARVALHO','CORONEL CARVALHO'),
('BR-CE-Fortaleza','parcel',2,'CORONELCHICO','CORONEL CHICO'),
('BR-CE-Fortaleza','parcel',2,'CORONELDE','CORONEL DE'),
('BR-CE-Fortaleza','parcel',2,'CORONELDIONÍSIO','CORONEL DIONÍSIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELDJALMA','CORONEL DJALMA'),
('BR-CE-Fortaleza','parcel',2,'CORONELDOMINGOS','CORONEL DOMINGOS'),
('BR-CE-Fortaleza','parcel',2,'CORONELDUARTE','CORONEL DUARTE'),
('BR-CE-Fortaleza','parcel',2,'CORONELERNESTO','CORONEL ERNESTO'),
('BR-CE-Fortaleza','parcel',2,'CORONELFABRICIANO','CORONEL FABRICIANO'),
('BR-CE-Fortaleza','parcel',2,'CORONELFERRAZ','CORONEL FERRAZ'),
('BR-CE-Fortaleza','parcel',2,'CORONELFRANCISCO','CORONEL FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'CORONELGONÇALO','CORONEL GONÇALO'),
('BR-CE-Fortaleza','parcel',2,'CORONELGUILHERME','CORONEL GUILHERME'),
('BR-CE-Fortaleza','parcel',2,'CORONELHELDER','CORONEL HELDER'),
('BR-CE-Fortaleza','parcel',2,'CORONELHONÓRIO','CORONEL HONÓRIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELJAIME','CORONEL JAIME'),
('BR-CE-Fortaleza','parcel',2,'CORONELJOAO','CORONEL JOAO'),
('BR-CE-Fortaleza','parcel',2,'CORONELJOAQUIM','CORONEL JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'CORONELJOSE','CORONEL JOSE'),
('BR-CE-Fortaleza','parcel',2,'CORONELJOSÉ','CORONEL JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'CORONELJOÃO','CORONEL JOÃO'),
('BR-CE-Fortaleza','parcel',2,'CORONELJUCA','CORONEL JUCA'),
('BR-CE-Fortaleza','parcel',2,'CORONELJUCÁ','CORONEL JUCÁ'),
('BR-CE-Fortaleza','parcel',2,'CORONELJUSTA','CORONEL JUSTA'),
('BR-CE-Fortaleza','parcel',2,'CORONELLEOCÁDIO','CORONEL LEOCÁDIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELLINHARES','CORONEL LINHARES'),
('BR-CE-Fortaleza','parcel',2,'CORONELLUIZ','CORONEL LUIZ'),
('BR-CE-Fortaleza','parcel',2,'CORONELMANOEL','CORONEL MANOEL'),
('BR-CE-Fortaleza','parcel',2,'CORONELMANUEL','CORONEL MANUEL'),
('BR-CE-Fortaleza','parcel',2,'CORONELMATOS','CORONEL MATOS'),
('BR-CE-Fortaleza','parcel',2,'CORONELMELQUIADES','CORONEL MELQUIADES'),
('BR-CE-Fortaleza','parcel',2,'CORONELMIGUEL','CORONEL MIGUEL'),
('BR-CE-Fortaleza','parcel',2,'CORONELMOZART','CORONEL MOZART'),
('BR-CE-Fortaleza','parcel',2,'CORONELNUNES','CORONEL NUNES'),
('BR-CE-Fortaleza','parcel',2,'CORONELOLEGÁRIO','CORONEL OLEGÁRIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELOTÁVIO','CORONEL OTÁVIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELPATRÍCIO','CORONEL PATRÍCIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELPERGENTINO','CORONEL PERGENTINO'),
('BR-CE-Fortaleza','parcel',2,'CORONELRIBEIRO','CORONEL RIBEIRO'),
('BR-CE-Fortaleza','parcel',2,'CORONELSALUSTIANO','CORONEL SALUSTIANO'),
('BR-CE-Fortaleza','parcel',2,'CORONELSALVIANO','CORONEL SALVIANO'),
('BR-CE-Fortaleza','parcel',2,'CORONELSOLON','CORONEL SOLON'),
('BR-CE-Fortaleza','parcel',2,'CORONELTIBÚRCIO','CORONEL TIBÚRCIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELVIRGILIO','CORONEL VIRGILIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELVIRGÍLIO','CORONEL VIRGÍLIO'),
('BR-CE-Fortaleza','parcel',2,'CORONELXAVIER','CORONEL XAVIER'),
('BR-CE-Fortaleza','parcel',2,'CORONELZACARIAS','CORONEL ZACARIAS'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOALFREDO','DEPUTADO ALFREDO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOCASTELO','DEPUTADO CASTELO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOFLÁVIO','DEPUTADO FLÁVIO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOFRANCISCO','DEPUTADO FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOJOAQUIM','DEPUTADO JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOJOEL','DEPUTADO JOEL'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOJOÃO','DEPUTADO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOLIBERATO','DEPUTADO LIBERATO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOMANOEL','DEPUTADO MANOEL'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOMATOSO','DEPUTADO MATOSO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOMOREIRA','DEPUTADO MOREIRA'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOOSWALDO','DEPUTADO OSWALDO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOPAULINO','DEPUTADO PAULINO'),
('BR-CE-Fortaleza','parcel',2,'DEPUTADOSEBASTIÃO','DEPUTADO SEBASTIÃO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORADALBERTO','DESEMBARGADOR ADALBERTO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORAGENOR','DESEMBARGADOR AGENOR'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORANTONIO','DESEMBARGADOR ANTONIO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORARMANDO','DESEMBARGADOR ARMANDO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORAVELAR','DESEMBARGADOR AVELAR'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORBALTAR','DESEMBARGADOR BALTAR'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORCARVALHO','DESEMBARGADOR CARVALHO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORCOELHO','DESEMBARGADOR COELHO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADOREURICO','DESEMBARGADOR EURICO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFAUSTINO','DESEMBARGADOR FAUSTINO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFELICIANO','DESEMBARGADOR FELICIANO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFELISMINO','DESEMBARGADOR FELISMINO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFELIX','DESEMBARGADOR FELIX'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFRANCISCO','DESEMBARGADOR FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFROTA','DESEMBARGADOR FROTA'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORFÉLIX','DESEMBARGADOR FÉLIX'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORGARCIA','DESEMBARGADOR GARCIA'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORGERMINIANO','DESEMBARGADOR GERMINIANO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORGOMES','DESEMBARGADOR GOMES'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORGONZAGA','DESEMBARGADOR GONZAGA'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORGUIMARÃES','DESEMBARGADOR GUIMARÃES'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORHERMES','DESEMBARGADOR HERMES'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORJOSÉ','DESEMBARGADOR JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORJOÃO','DESEMBARGADOR JOÃO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORJUCÁ','DESEMBARGADOR JUCÁ'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORLAURO','DESEMBARGADOR LAURO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORLEITE','DESEMBARGADOR LEITE'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORLUÍS','DESEMBARGADOR LUÍS'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORMANOEL','DESEMBARGADOR MANOEL'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORMOREIRA','DESEMBARGADOR MOREIRA'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADOROTACÍLIO','DESEMBARGADOR OTACÍLIO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORPAULO','DESEMBARGADOR PAULO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORPRAXEDES','DESEMBARGADOR PRAXEDES'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORRAIMUNDO','DESEMBARGADOR RAIMUNDO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORUBIRAJARA','DESEMBARGADOR UBIRAJARA'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORVALDETÁRIO','DESEMBARGADOR VALDETÁRIO'),
('BR-CE-Fortaleza','parcel',2,'DESEMBARGADORWALDEMAR','DESEMBARGADOR WALDEMAR'),
('BR-CE-Fortaleza','parcel',2,'DOMALUISIO','DOM ALUISIO'),
('BR-CE-Fortaleza','parcel',2,'DOMAMARO','DOM AMARO'),
('BR-CE-Fortaleza','parcel',2,'DOMANTONIO','DOM ANTONIO'),
('BR-CE-Fortaleza','parcel',2,'DOMAUBERGIO','DOM AUBERGIO'),
('BR-CE-Fortaleza','parcel',2,'DOMAURELIANO','DOM AURELIANO'),
('BR-CE-Fortaleza','parcel',2,'DOMBOSCO','DOM BOSCO'),
('BR-CE-Fortaleza','parcel',2,'DOMCARLOTO','DOM CARLOTO'),
('BR-CE-Fortaleza','parcel',2,'DOMCARMELO','DOM CARMELO'),
('BR-CE-Fortaleza','parcel',2,'DOMDELGADO','DOM DELGADO'),
('BR-CE-Fortaleza','parcel',2,'DOMEXPEDITO','DOM EXPEDITO'),
('BR-CE-Fortaleza','parcel',2,'DOMGUIDO','DOM GUIDO'),
('BR-CE-Fortaleza','parcel',2,'DOMHELDER','DOM HELDER'),
('BR-CE-Fortaleza','parcel',2,'DOMHENRIQUE','DOM HENRIQUE'),
('BR-CE-Fortaleza','parcel',2,'DOMHOMERO','DOM HOMERO'),
('BR-CE-Fortaleza','parcel',2,'DOMHÉLIO','DOM HÉLIO'),
('BR-CE-Fortaleza','parcel',2,'DOMJERÔNIMO','DOM JERÔNIMO'),
('BR-CE-Fortaleza','parcel',2,'DOMJOAQUIM','DOM JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'DOMJOSÉ','DOM JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'DOMLINO','DOM LINO'),
('BR-CE-Fortaleza','parcel',2,'DOMLOURENÇO','DOM LOURENÇO'),
('BR-CE-Fortaleza','parcel',2,'DOMLUSTOSA','DOM LUSTOSA'),
('BR-CE-Fortaleza','parcel',2,'DOMLUÍS','DOM LUÍS'),
('BR-CE-Fortaleza','parcel',2,'DOMMANUEL','DOM MANUEL'),
('BR-CE-Fortaleza','parcel',2,'DOMMARCOS','DOM MARCOS'),
('BR-CE-Fortaleza','parcel',2,'DOMMAURICIO','DOM MAURICIO'),
('BR-CE-Fortaleza','parcel',2,'DOMOSCAR','DOM OSCAR'),
('BR-CE-Fortaleza','parcel',2,'DOMPEDRO','DOM PEDRO'),
('BR-CE-Fortaleza','parcel',2,'DOMQUINTINO','DOM QUINTINO'),
('BR-CE-Fortaleza','parcel',2,'DOMREGO','DOM REGO'),
('BR-CE-Fortaleza','parcel',2,'DOMSEBASTIÃO','DOM SEBASTIÃO'),
('BR-CE-Fortaleza','parcel',2,'DOMSILVÉRIO','DOM SILVÉRIO'),
('BR-CE-Fortaleza','parcel',2,'DOMVITAL','DOM VITAL'),
('BR-CE-Fortaleza','parcel',2,'DOMXISTO','DOM XISTO'),
('BR-CE-Fortaleza','parcel',2,'DONAADAIL','DONA ADAIL'),
('BR-CE-Fortaleza','parcel',2,'DONAALEXANDRINA','DONA ALEXANDRINA'),
('BR-CE-Fortaleza','parcel',2,'DONAAMÉLIA','DONA AMÉLIA'),
('BR-CE-Fortaleza','parcel',2,'DONABELA','DONA BELA'),
('BR-CE-Fortaleza','parcel',2,'DONAESTER','DONA ESTER'),
('BR-CE-Fortaleza','parcel',2,'DONAFEDERALINA','DONA FEDERALINA'),
('BR-CE-Fortaleza','parcel',2,'DONAIRENE','DONA IRENE'),
('BR-CE-Fortaleza','parcel',2,'DONAIZABEL','DONA IZABEL'),
('BR-CE-Fortaleza','parcel',2,'DONAJOSEFA','DONA JOSEFA'),
('BR-CE-Fortaleza','parcel',2,'DONAJULIETA','DONA JULIETA'),
('BR-CE-Fortaleza','parcel',2,'DONALEOPOLDINA','DONA LEOPOLDINA'),
('BR-CE-Fortaleza','parcel',2,'DONALOURDES','DONA LOURDES'),
('BR-CE-Fortaleza','parcel',2,'DONAMAROQUINHA','DONA MAROQUINHA'),
('BR-CE-Fortaleza','parcel',2,'DONAMENDINHA','DONA MENDINHA'),
('BR-CE-Fortaleza','parcel',2,'DONAROSINHA','DONA ROSINHA'),
('BR-CE-Fortaleza','parcel',2,'DONASARA','DONA SARA'),
('BR-CE-Fortaleza','parcel',2,'DONATILIA','DONA TILIA'),
('BR-CE-Fortaleza','parcel',2,'DONATÍLIA','DONA TÍLIA'),
('BR-CE-Fortaleza','parcel',2,'DONAZENAIDE','DONA ZENAIDE'),


('BR-CE-Fortaleza','parcel',2,'DOUTORABDENAGO','DOUTOR ABDENAGO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORADHEMAR','DOUTOR ADHEMAR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORADJEMIR','DOUTOR ADJEMIR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAIRTON','DOUTOR AIRTON'),
('BR-CE-Fortaleza','parcel',2,'DOUTORALDY','DOUTOR ALDY'),
('BR-CE-Fortaleza','parcel',2,'DOUTORALENCAR','DOUTOR ALENCAR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORALFREDO','DOUTOR ALFREDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORALMEIDA','DOUTOR ALMEIDA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORALÍSIO','DOUTOR ALÍSIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAMADEU','DOUTOR AMADEU'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAMARIA','DOUTORA MARIA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAMAURI','DOUTOR AMAURI'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAMBRÓSIO','DOUTOR AMBRÓSIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORANTÔNIO','DOUTOR ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORASOCORRO','DOUTORA SOCORRO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORATUALPA','DOUTOR ATUALPA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAUGUSTO','DOUTOR AUGUSTO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAVANDA','DOUTORA VANDA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORAWANDA','DOUTORA WANDA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORBATISTA','DOUTOR BATISTA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORBERNARDO','DOUTOR BERNARDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORBEZERRINHA','DOUTOR BEZERRINHA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORCARLOS','DOUTOR CARLOS'),
('BR-CE-Fortaleza','parcel',2,'DOUTORCATUNDA','DOUTOR CATUNDA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORCODES','DOUTOR CODES'),
('BR-CE-Fortaleza','parcel',2,'DOUTORCORREIA','DOUTOR CORREIA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORCOSTA','DOUTOR COSTA'),
('BR-CE-Fortaleza','parcel',2,'DOUTOREDMILSON','DOUTOR EDMILSON'),
('BR-CE-Fortaleza','parcel',2,'DOUTOREDSON','DOUTOR EDSON'),
('BR-CE-Fortaleza','parcel',2,'DOUTOREDUARDO','DOUTOR EDUARDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORELIZEU','DOUTOR ELIZEU'),
('BR-CE-Fortaleza','parcel',2,'DOUTOREMÍLIO','DOUTOR EMÍLIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORERNESTO','DOUTOR ERNESTO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORESMERINO','DOUTOR ESMERINO'),
('BR-CE-Fortaleza','parcel',2,'DOUTOREXPEDITO','DOUTOR EXPEDITO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORFERNANDO','DOUTOR FERNANDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORFRANCISCO','DOUTOR FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORGERARDO','DOUTOR GERARDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORGILBERTO','DOUTOR GILBERTO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORGUIDO','DOUTOR GUIDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORHERMES','DOUTOR HERMES'),
('BR-CE-Fortaleza','parcel',2,'DOUTORHUGO','DOUTOR HUGO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORHUMBERTO','DOUTOR HUMBERTO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORHÉLIO','DOUTOR HÉLIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORITAMAR','DOUTOR ITAMAR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJOAQUIM','DOUTOR JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJORGE','DOUTOR JORGE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJOSE','DOUTOR JOSE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJOSÉ','DOUTOR JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJOÃO','DOUTOR JOÃO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJULIO','DOUTOR JULIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJURANDYR','DOUTOR JURANDYR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJUSTA','DOUTOR JUSTA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORJÁDER','DOUTOR JÁDER'),
('BR-CE-Fortaleza','parcel',2,'DOUTORLAUDELINO','DOUTOR LAUDELINO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORLAURO','DOUTOR LAURO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORLUIS','DOUTOR LUIS'),
('BR-CE-Fortaleza','parcel',2,'DOUTORLUIZ','DOUTOR LUIZ'),
('BR-CE-Fortaleza','parcel',2,'DOUTORLUÍS','DOUTOR LUÍS'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMANOEL','DOUTOR MANOEL'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMANUEL','DOUTOR MANUEL'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMARLIO','DOUTOR MARLIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMEDEIRINHO','DOUTOR MEDEIRINHO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMENDEL','DOUTOR MENDEL'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMIGUEL','DOUTOR MIGUEL'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMIRES','DOUTOR MIRES'),
('BR-CE-Fortaleza','parcel',2,'DOUTORMOZART','DOUTOR MOZART'),
('BR-CE-Fortaleza','parcel',2,'DOUTORONOFRE','DOUTOR ONOFRE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPAULO','DOUTOR PAULO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPEDRO','DOUTOR PEDRO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPERGENTINO','DOUTOR PERGENTINO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPERIGUARI','DOUTOR PERIGUARI'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPERILO','DOUTOR PERILO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPIO','DOUTOR PIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPLACIDO','DOUTOR PLACIDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPONTES','DOUTOR PONTES'),
('BR-CE-Fortaleza','parcel',2,'DOUTORPROCÓPIO','DOUTOR PROCÓPIO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORQUIXADÁ','DOUTOR QUIXADÁ'),
('BR-CE-Fortaleza','parcel',2,'DOUTORRAIMUNDO','DOUTOR RAIMUNDO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORRATISBONA','DOUTOR RATISBONA'),
('BR-CE-Fortaleza','parcel',2,'DOUTORRAUL','DOUTOR RAUL'),
('BR-CE-Fortaleza','parcel',2,'DOUTORRIBAMAR','DOUTOR RIBAMAR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORRODRIGO','DOUTOR RODRIGO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORSAMUEL','DOUTOR SAMUEL'),
('BR-CE-Fortaleza','parcel',2,'DOUTORSEIXAS','DOUTOR SEIXAS'),
('BR-CE-Fortaleza','parcel',2,'DOUTORSILAS','DOUTOR SILAS'),
('BR-CE-Fortaleza','parcel',2,'DOUTORSULIANO','DOUTOR SULIANO'),
('BR-CE-Fortaleza','parcel',2,'DOUTORTHEBERGE','DOUTOR THEBERGE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORTHOMPSON','DOUTOR THOMPSON'),
('BR-CE-Fortaleza','parcel',2,'DOUTORTURBAY','DOUTOR TURBAY'),
('BR-CE-Fortaleza','parcel',2,'DOUTORVALDIR','DOUTOR VALDIR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORVALE','DOUTOR VALE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORVALMIR','DOUTOR VALMIR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORVICENTE','DOUTOR VICENTE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORVITOR','DOUTOR VITOR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORWALDEMAR','DOUTOR WALDEMAR'),
('BR-CE-Fortaleza','parcel',2,'DOUTORWALDER','DOUTOR WALDER'),
('BR-CE-Fortaleza','parcel',2,'DOUTORWALMIQUE','DOUTOR WALMIQUE'),
('BR-CE-Fortaleza','parcel',2,'DOUTORWALTER','DOUTOR WALTER'),
('BR-CE-Fortaleza','parcel',2,'DOUTORZELITO','DOUTOR ZELITO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROAGRÔNOMO','ENGENHEIRO AGRÔNOMO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROALBERTO','ENGENHEIRO ALBERTO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROANTÔNIO','ENGENHEIRO ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROCLÉBER','ENGENHEIRO CLÉBER'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIRODEMONTIER','ENGENHEIRO DEMONTIER'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROEDMUNDO','ENGENHEIRO EDMUNDO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROHEITOR','ENGENHEIRO HEITOR'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROHENRIQUE','ENGENHEIRO HENRIQUE'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROHUMBERTO','ENGENHEIRO HUMBERTO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROJOSE','ENGENHEIRO JOSE'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROJOÃO','ENGENHEIRO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROLEAL','ENGENHEIRO LEAL'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROLIMA','ENGENHEIRO LIMA'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROLUIZ','ENGENHEIRO LUIZ'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROMARIA','ENGENHEIRO MARIA'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROMELO','ENGENHEIRO MELO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIRONEREU','ENGENHEIRO NEREU'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROPAULO','ENGENHEIRO PAULO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROPLÁCIDO','ENGENHEIRO PLÁCIDO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIRORONALDO','ENGENHEIRO RONALDO'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROSAMIR','ENGENHEIRO SAMIR'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROSANTANA','ENGENHEIRO SANTANA'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROSERAINE','ENGENHEIRO SERAINE'),
('BR-CE-Fortaleza','parcel',2,'ENGENHEIROSÍLVIO','ENGENHEIRO SÍLVIO'),
('BR-CE-Fortaleza','parcel',2,'FISCALASSIS','FISCAL ASSIS'),
('BR-CE-Fortaleza','parcel',2,'FISCALPERDIGÃO','FISCAL PERDIGÃO'),
('BR-CE-Fortaleza','parcel',2,'FISCALSARAIVA','FISCAL SARAIVA'),
('BR-CE-Fortaleza','parcel',2,'FISCALVIEIRA','FISCAL VIEIRA'),
('BR-CE-Fortaleza','parcel',2,'FREIBENÍCIO','FREI BENÍCIO'),
('BR-CE-Fortaleza','parcel',2,'FREIBERNARDINO','FREI BERNARDINO'),
('BR-CE-Fortaleza','parcel',2,'FREICANECA','FREI CANECA'),
('BR-CE-Fortaleza','parcel',2,'FREICASSIANO','FREI CASSIANO'),
('BR-CE-Fortaleza','parcel',2,'FREICIRILO','FREI CIRILO'),
('BR-CE-Fortaleza','parcel',2,'FREIDAMIAO','FREI DAMIAO'),
('BR-CE-Fortaleza','parcel',2,'FREIGALVÃO','FREI GALVÃO'),
('BR-CE-Fortaleza','parcel',2,'FREIGASPAR','FREI GASPAR'),
('BR-CE-Fortaleza','parcel',2,'FREIGERALDO','FREI GERALDO'),
('BR-CE-Fortaleza','parcel',2,'FREIHENRIQUE','FREI HENRIQUE'),
('BR-CE-Fortaleza','parcel',2,'FREIHUMBERTO','FREI HUMBERTO'),
('BR-CE-Fortaleza','parcel',2,'FREIJOSÉ','FREI JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'FREIMANSUETO','FREI MANSUETO'),
('BR-CE-Fortaleza','parcel',2,'FREIMARCELINO','FREI MARCELINO'),
('BR-CE-Fortaleza','parcel',2,'FREIMATIAS','FREI MATIAS'),
('BR-CE-Fortaleza','parcel',2,'FREIODILON','FREI ODILON'),
('BR-CE-Fortaleza','parcel',2,'FREIORLANDO','FREI ORLANDO'),
('BR-CE-Fortaleza','parcel',2,'FREISERAFIM','FREI SERAFIM'),
('BR-CE-Fortaleza','parcel',2,'FREITAS','FREI TAS'),
('BR-CE-Fortaleza','parcel',2,'FREITEOBALDO','FREI TEOBALDO'),
('BR-CE-Fortaleza','parcel',2,'FREITEODORO','FREI TEODORO'),
('BR-CE-Fortaleza','parcel',2,'FREITITO','FREI TITO'),
('BR-CE-Fortaleza','parcel',2,'FREIVICENTE','FREI VICENTE'),
('BR-CE-Fortaleza','parcel',2,'FREIVIDAL','FREI VIDAL'),
('BR-CE-Fortaleza','parcel',2,'GENERALAFONSO','GENERAL AFONSO'),
('BR-CE-Fortaleza','parcel',2,'GENERALALÍPIO','GENERAL ALÍPIO'),
('BR-CE-Fortaleza','parcel',2,'GENERALBERNARDO','GENERAL BERNARDO'),
('BR-CE-Fortaleza','parcel',2,'GENERALBEZERRIL','GENERAL BEZERRIL'),
('BR-CE-Fortaleza','parcel',2,'GENERALCAIADO','GENERAL CAIADO'),
('BR-CE-Fortaleza','parcel',2,'GENERALCASTELO','GENERAL CASTELO'),
('BR-CE-Fortaleza','parcel',2,'GENERALCLARINDO','GENERAL CLARINDO'),
('BR-CE-Fortaleza','parcel',2,'GENERALCORDEIRO','GENERAL CORDEIRO'),
('BR-CE-Fortaleza','parcel',2,'GENERALCOSTA','GENERAL COSTA'),
('BR-CE-Fortaleza','parcel',2,'GENERALDUTRA','GENERAL DUTRA'),
('BR-CE-Fortaleza','parcel',2,'GENERALEURICO','GENERAL EURICO'),
('BR-CE-Fortaleza','parcel',2,'GENERALJOAQUIM','GENERAL JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'GENERALJOÃO','GENERAL JOÃO'),
('BR-CE-Fortaleza','parcel',2,'GENERALLIMA','GENERAL LIMA'),
('BR-CE-Fortaleza','parcel',2,'GENERALMELO','GENERAL MELO'),
('BR-CE-Fortaleza','parcel',2,'GENERALMUNIZ','GENERAL MUNIZ'),
('BR-CE-Fortaleza','parcel',2,'GENERALMURILO','GENERAL MURILO'),
('BR-CE-Fortaleza','parcel',2,'GENERALMÁRIO','GENERAL MÁRIO'),
('BR-CE-Fortaleza','parcel',2,'GENERALONOFRE','GENERAL ONOFRE'),
('BR-CE-Fortaleza','parcel',2,'GENERALOSÓRIO','GENERAL OSÓRIO'),
('BR-CE-Fortaleza','parcel',2,'GENERALOTÁVIO','GENERAL OTÁVIO'),
('BR-CE-Fortaleza','parcel',2,'GENERALPIRAGIBE','GENERAL PIRAGIBE'),
('BR-CE-Fortaleza','parcel',2,'GENERALRABELO','GENERAL RABELO'),
('BR-CE-Fortaleza','parcel',2,'GENERALRANGEL','GENERAL RANGEL'),
('BR-CE-Fortaleza','parcel',2,'GENERALROMMEL','GENERAL ROMMEL'),
('BR-CE-Fortaleza','parcel',2,'GENERALSAMPAIO','GENERAL SAMPAIO'),
('BR-CE-Fortaleza','parcel',2,'GENERALSILVA','GENERAL SILVA'),
('BR-CE-Fortaleza','parcel',2,'GENERALTERTULIANO','GENERAL TERTULIANO'),
('BR-CE-Fortaleza','parcel',2,'GENERALTOMÉ','GENERAL TOMÉ'),
('BR-CE-Fortaleza','parcel',2,'GOVERNADORFAUSTINO','GOVERNADOR FAUSTINO'),
('BR-CE-Fortaleza','parcel',2,'GOVERNADORJOAO','GOVERNADOR JOAO'),
('BR-CE-Fortaleza','parcel',2,'GOVERNADORLEONEL','GOVERNADOR LEONEL'),
('BR-CE-Fortaleza','parcel',2,'GOVERNADORMANOEL','GOVERNADOR MANOEL'),
('BR-CE-Fortaleza','parcel',2,'GOVERNADORPARSIFAL','GOVERNADOR PARSIFAL'),
('BR-CE-Fortaleza','parcel',2,'GOVERNADORSAMPAIO','GOVERNADOR SAMPAIO'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTAANTONIO','JORNALISTA ANTONIO'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTACESAR','JORNALISTA CESAR'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTADANIEL','JORNALISTA DANIEL'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTADEOLINDO','JORNALISTA DEOLINDO'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTANERTAN','JORNALISTA NERTAN'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTAOLAVO','JORNALISTA OLAVO'),
('BR-CE-Fortaleza','parcel',2,'JORNALISTATHOMAZ','JORNALISTA THOMAZ'),
('BR-CE-Fortaleza','parcel',2,'JUIZFRANCISCO','JUIZ FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'JUIZRENATO','JUIZ RENATO'),
('BR-CE-Fortaleza','parcel',2,'LIVREIROARLINDO','LIVREIRO ARLINDO'),
('BR-CE-Fortaleza','parcel',2,'LIVREIROEDÉSIO','LIVREIRO EDÉSIO'),
('BR-CE-Fortaleza','parcel',2,'LIVREIROGUALTER','LIVREIRO GUALTER'),
('BR-CE-Fortaleza','parcel',2,'LIVREIROLUÍS','LIVREIRO LUÍS'),
('BR-CE-Fortaleza','parcel',2,'LIVREIROPOLARY','LIVREIRO POLARY'),
('BR-CE-Fortaleza','parcel',2,'MADREELISA','MADRE ELISA'),
('BR-CE-Fortaleza','parcel',2,'MADRESILVA','MADRE SILVA'),
('BR-CE-Fortaleza','parcel',2,'MADRETEREZA','MADRE TEREZA'),
('BR-CE-Fortaleza','parcel',2,'MAESTROLISBOA','MAESTRO LISBOA'),
('BR-CE-Fortaleza','parcel',2,'MAESTRONEO','MAESTRO NEO'),
('BR-CE-Fortaleza','parcel',2,'MAESTROSILVA','MAESTRO SILVA'),
('BR-CE-Fortaleza','parcel',2,'MAJORADELINO','MAJOR ADELINO'),
('BR-CE-Fortaleza','parcel',2,'MAJORASSIS','MAJOR ASSIS'),
('BR-CE-Fortaleza','parcel',2,'MAJORCELESTINO','MAJOR CELESTINO'),
('BR-CE-Fortaleza','parcel',2,'MAJORFACUNDO','MAJOR FACUNDO'),
('BR-CE-Fortaleza','parcel',2,'MAJORGERARDO','MAJOR GERARDO'),
('BR-CE-Fortaleza','parcel',2,'MAJORJOAO','MAJOR JOAO'),
('BR-CE-Fortaleza','parcel',2,'MAJORJOSÉ','MAJOR JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'MAJORLADISLAU','MAJOR LADISLAU'),
('BR-CE-Fortaleza','parcel',2,'MAJORLANDIA','MAJOR LANDIA'),
('BR-CE-Fortaleza','parcel',2,'MAJORLAURINDO','MAJOR LAURINDO'),
('BR-CE-Fortaleza','parcel',2,'MAJORMONTENEGRO','MAJOR MONTENEGRO'),
('BR-CE-Fortaleza','parcel',2,'MAJORMOREIRA','MAJOR MOREIRA'),
('BR-CE-Fortaleza','parcel',2,'MAJOROCTACÍLIO','MAJOR OCTACÍLIO'),
('BR-CE-Fortaleza','parcel',2,'MAJORPEDRO','MAJOR PEDRO'),
('BR-CE-Fortaleza','parcel',2,'MAJORSUCUPIRA','MAJOR SUCUPIRA'),
('BR-CE-Fortaleza','parcel',2,'MAJORTELESFORO','MAJOR TELESFORO'),
('BR-CE-Fortaleza','parcel',2,'MAJORVAZ','MAJOR VAZ'),
('BR-CE-Fortaleza','parcel',2,'MAJORVERÍSSIMO','MAJOR VERÍSSIMO'),
('BR-CE-Fortaleza','parcel',2,'MAJORVIRGILIO','MAJOR VIRGILIO'),
('BR-CE-Fortaleza','parcel',2,'MAJORWEYNE','MAJOR WEYNE'),
('BR-CE-Fortaleza','parcel',2,'MAJORWILSON','MAJOR WILSON'),
('BR-CE-Fortaleza','parcel',2,'MARECHALBITTENCOURT','MARECHAL BITTENCOURT'),
('BR-CE-Fortaleza','parcel',2,'MARECHALDEODORO','MARECHAL DEODORO'),
('BR-CE-Fortaleza','parcel',2,'MARECHALLOTT','MARECHAL LOTT'),
('BR-CE-Fortaleza','parcel',2,'MARECHALMASCARENHAS','MARECHAL MASCARENHAS'),
('BR-CE-Fortaleza','parcel',2,'MARECHALNAPION','MARECHAL NAPION'),
('BR-CE-Fortaleza','parcel',2,'MARECHALRONDON','MARECHAL RONDON'),
('BR-CE-Fortaleza','parcel',2,'MARQUESABRANTES','*MARQUESABRANTES'),
('BR-CE-Fortaleza','parcel',2,'MINISTROABNER','MINISTRO ABNER'),
('BR-CE-Fortaleza','parcel',2,'MINISTROALBUQUERQUE','MINISTRO ALBUQUERQUE'),
('BR-CE-Fortaleza','parcel',2,'MINISTROANTÔNIO','MINISTRO ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'MINISTROEDUARDO','MINISTRO EDUARDO'),
('BR-CE-Fortaleza','parcel',2,'MINISTROJOAQUIM','MINISTRO JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'MINISTROJOSÉ','MINISTRO JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'MINISTROPETRÔNIO','MINISTRO PETRÔNIO'),
('BR-CE-Fortaleza','parcel',2,'MINISTROSERGIO','MINISTRO SERGIO'),
('BR-CE-Fortaleza','parcel',2,'MISSIONÁRIOARTHUR','MISSIONÁRIO ARTHUR'),
('BR-CE-Fortaleza','parcel',2,'MISSIONÁRIOOLIVEIRA','MISSIONÁRIO OLIVEIRA'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORAGOSTINHO','MONSENHOR AGOSTINHO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORAMARÍLIO','MONSENHOR AMARÍLIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORAMAURICIO','MONSENHOR AMAURICIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORANTERO','MONSENHOR ANTERO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORANTÔNIO','MONSENHOR ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORAZARIAS','MONSENHOR AZARIAS'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORBEZERRA','MONSENHOR BEZERRA'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORBRUNO','MONSENHOR BRUNO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORCARNEIRO','MONSENHOR CARNEIRO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORCATÃO','MONSENHOR CATÃO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORDANTAS','MONSENHOR DANTAS'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORDOURADO','MONSENHOR DOURADO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORFURTADO','MONSENHOR FURTADO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORHELIO','MONSENHOR HELIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORHIPÓLITO','MONSENHOR HIPÓLITO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORHÉLIO','MONSENHOR HÉLIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORJOÃO','MONSENHOR JOÃO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORLEOPOLDO','MONSENHOR LEOPOLDO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORLIBERATO','MONSENHOR LIBERATO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORLUÍS','MONSENHOR LUÍS'),
('BR-CE-Fortaleza','parcel',2,'MONSENHOROTAVIO','MONSENHOR OTAVIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHOROTÁVIO','MONSENHOR OTÁVIO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORPAULO','MONSENHOR PAULO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORPINTO','MONSENHOR PINTO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORROSA','MONSENHOR ROSA'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORSABINO','MONSENHOR SABINO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORSALAZAR','MONSENHOR SALAZAR'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORSALVIANO','MONSENHOR SALVIANO'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORTABOSA','MONSENHOR TABOSA'),
('BR-CE-Fortaleza','parcel',2,'MONSENHORVICENTE','MONSENHOR VICENTE'),
('BR-CE-Fortaleza','parcel',2,'NATURALISTAFEIJO','NATURALISTA FEIJO'),
('BR-CE-Fortaleza','parcel',2,'PADREALANO','PADRE ALANO'),
('BR-CE-Fortaleza','parcel',2,'PADREALTO','PADRE ALTO'),
('BR-CE-Fortaleza','parcel',2,'PADREALUÍSIO','PADRE ALUÍSIO'),
('BR-CE-Fortaleza','parcel',2,'PADREAMBRÓSIO','PADRE AMBRÓSIO'),
('BR-CE-Fortaleza','parcel',2,'PADREANCHIETA','PADRE ANCHIETA'),
('BR-CE-Fortaleza','parcel',2,'PADREANDRADE','PADRE ANDRADE'),
('BR-CE-Fortaleza','parcel',2,'PADREANTONINO','PADRE ANTONINO'),
('BR-CE-Fortaleza','parcel',2,'PADREANTÔNIO','PADRE ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'PADREARIMATEIA','PADRE ARIMATEIA'),
('BR-CE-Fortaleza','parcel',2,'PADREARTUR','PADRE ARTUR'),
('BR-CE-Fortaleza','parcel',2,'PADREASCENÇO','PADRE ASCENÇO'),
('BR-CE-Fortaleza','parcel',2,'PADREATAIDE','PADRE ATAIDE'),
('BR-CE-Fortaleza','parcel',2,'PADREAUZI','PADRE AUZI'),
('BR-CE-Fortaleza','parcel',2,'PADREBARBOSA','PADRE BARBOSA'),
('BR-CE-Fortaleza','parcel',2,'PADREBERNARDO','PADRE BERNARDO'),
('BR-CE-Fortaleza','parcel',2,'PADRECARLOS','PADRE CARLOS'),
('BR-CE-Fortaleza','parcel',2,'PADRECHEVALIER','PADRE CHEVALIER'),
('BR-CE-Fortaleza','parcel',2,'PADRECICERO','PADRE CICERO'),
('BR-CE-Fortaleza','parcel',2,'PADRECLIMÉRIO','PADRE CLIMÉRIO'),
('BR-CE-Fortaleza','parcel',2,'PADRECONSTANTINO','PADRE CONSTANTINO'),
('BR-CE-Fortaleza','parcel',2,'PADRECíCERO','PADRE CíCERO'),
('BR-CE-Fortaleza','parcel',2,'PADREEDUARDO','PADRE EDUARDO'),
('BR-CE-Fortaleza','parcel',2,'PADREELIAS','PADRE ELIAS'),
('BR-CE-Fortaleza','parcel',2,'PADREERIDIAN','PADRE ERIDIAN'),
('BR-CE-Fortaleza','parcel',2,'PADREEZEQUIEL','PADRE EZEQUIEL'),
('BR-CE-Fortaleza','parcel',2,'PADREFRANCISCO','PADRE FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'PADREFROTA','PADRE FROTA'),
('BR-CE-Fortaleza','parcel',2,'PADREGALVÃO','PADRE GALVÃO'),
('BR-CE-Fortaleza','parcel',2,'PADREGERMANO','PADRE GERMANO'),
('BR-CE-Fortaleza','parcel',2,'PADREGONÇALVES','PADRE GONÇALVES'),
('BR-CE-Fortaleza','parcel',2,'PADREGRAÇA','PADRE GRAÇA'),
('BR-CE-Fortaleza','parcel',2,'PADREGUERRA','PADRE GUERRA'),
('BR-CE-Fortaleza','parcel',2,'PADREGUILHERME','PADRE GUILHERME'),
('BR-CE-Fortaleza','parcel',2,'PADREGUILHERMINO','PADRE GUILHERMINO'),
('BR-CE-Fortaleza','parcel',2,'PADREHENRIQUE','PADRE HENRIQUE'),
('BR-CE-Fortaleza','parcel',2,'PADREIBIAPINA','PADRE IBIAPINA'),
('BR-CE-Fortaleza','parcel',2,'PADREJANUÁRIO','PADRE JANUÁRIO'),
('BR-CE-Fortaleza','parcel',2,'PADREJOAQUIM','PADRE JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'PADREJOSINO','PADRE JOSINO'),
('BR-CE-Fortaleza','parcel',2,'PADREJOSÉ','PADRE JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'PADREJOÃO','PADRE JOÃO'),
('BR-CE-Fortaleza','parcel',2,'PADREJUSTINO','PADRE JUSTINO'),
('BR-CE-Fortaleza','parcel',2,'PADRELEOPOLDO','PADRE LEOPOLDO'),
('BR-CE-Fortaleza','parcel',2,'PADRELINHARES','PADRE LINHARES'),
('BR-CE-Fortaleza','parcel',2,'PADRELUIS','PADRE LUIS'),
('BR-CE-Fortaleza','parcel',2,'PADRELUIZ','PADRE LUIZ'),
('BR-CE-Fortaleza','parcel',2,'PADREMACEDO','PADRE MACEDO'),
('BR-CE-Fortaleza','parcel',2,'PADREMANUEL','PADRE MANUEL'),
('BR-CE-Fortaleza','parcel',2,'PADREMATOS','PADRE MATOS'),
('BR-CE-Fortaleza','parcel',2,'PADREMAXIMILIANO','PADRE MAXIMILIANO'),
('BR-CE-Fortaleza','parcel',2,'PADREMIGUELINHO','PADRE MIGUELINHO'),
('BR-CE-Fortaleza','parcel',2,'PADREMOACIR','PADRE MOACIR'),
('BR-CE-Fortaleza','parcel',2,'PADREMONTEIRO','PADRE MONTEIRO'),
('BR-CE-Fortaleza','parcel',2,'PADREMORORÓ','PADRE MORORÓ'),
('BR-CE-Fortaleza','parcel',2,'PADREMÁXIMO','PADRE MÁXIMO'),
('BR-CE-Fortaleza','parcel',2,'PADRENELSON','PADRE NELSON'),
('BR-CE-Fortaleza','parcel',2,'PADRENÓBREGA','PADRE NÓBREGA'),
('BR-CE-Fortaleza','parcel',2,'PADREPALHANO','PADRE PALHANO'),
('BR-CE-Fortaleza','parcel',2,'PADREPAULINO','PADRE PAULINO'),
('BR-CE-Fortaleza','parcel',2,'PADREPEDRO','PADRE PEDRO'),
('BR-CE-Fortaleza','parcel',2,'PADREPERDIGÃO','PADRE PERDIGÃO'),
('BR-CE-Fortaleza','parcel',2,'PADREPHILLIPE','PADRE PHILLIPE'),
('BR-CE-Fortaleza','parcel',2,'PADREPIO','PADRE PIO'),
('BR-CE-Fortaleza','parcel',2,'PADREPITA','PADRE PITA'),
('BR-CE-Fortaleza','parcel',2,'PADREQUINDERÉ','PADRE QUINDERÉ'),
('BR-CE-Fortaleza','parcel',2,'PADRERAIMUNDO','PADRE RAIMUNDO'),
('BR-CE-Fortaleza','parcel',2,'PADRERODOLFO','PADRE RODOLFO'),
('BR-CE-Fortaleza','parcel',2,'PADREROMA','PADRE ROMA'),
('BR-CE-Fortaleza','parcel',2,'PADRESAMUEL','PADRE SAMUEL'),
('BR-CE-Fortaleza','parcel',2,'PADRESEVERIANO','PADRE SEVERIANO'),
('BR-CE-Fortaleza','parcel',2,'PADRESÁ','PADRE SÁ'),
('BR-CE-Fortaleza','parcel',2,'PADRETEODORO','PADRE TEODORO'),
('BR-CE-Fortaleza','parcel',2,'PADREVALDEVINO','PADRE VALDEVINO'),
('BR-CE-Fortaleza','parcel',2,'PADREVALDIR','PADRE VALDIR'),
('BR-CE-Fortaleza','parcel',2,'PADREWASSEN','PADRE WASSEN'),
('BR-CE-Fortaleza','parcel',2,'PASTORJOÃO','PASTOR JOÃO'),
('BR-CE-Fortaleza','parcel',2,'PASTORSAMUEL','PASTOR SAMUEL'),
('BR-CE-Fortaleza','parcel',2,'PESCADORCHICO','PESCADOR CHICO'),
('BR-CE-Fortaleza','parcel',2,'PESCADORFRANCISCO','PESCADOR FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'PESCADORJERONIMO','PESCADOR JERONIMO'),
('BR-CE-Fortaleza','parcel',2,'PREFEITOEVANDRO','PREFEITO EVANDRO'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTEARTUR','PRESIDENTE ARTUR'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTECASTELO','PRESIDENTE CASTELO'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTECOSTA','PRESIDENTE COSTA'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTEHERNESTO','PRESIDENTE HERNESTO'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTEJUSCELINO','PRESIDENTE JUSCELINO'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTEPRUDENTE','PRESIDENTE PRUDENTE'),
('BR-CE-Fortaleza','parcel',2,'PRESIDENTEVARGAS','PRESIDENTE VARGAS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORAAIDA','PROFESSORA AIDA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORAALBANISA','PROFESSORA ALBANISA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORAALDACI','PROFESSORA ALDACI'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORADROALDO','PROFESSOR ADROALDO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORAGERALDA','PROFESSORA GERALDA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORALMINO','PROFESSOR ALMINO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORALOYSIO','PROFESSOR ALOYSIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORALVARO','PROFESSOR ALVARO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORAMARIA','PROFESSORA MARIA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORAMARÍLIO','PROFESSOR AMARÍLIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORANACLETO','PROFESSOR ANACLETO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORANTÔNIO','PROFESSOR ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORARAÚJO','PROFESSOR ARAÚJO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORARI','PROFESSOR ARI'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORASTELLA','PROFESSOR ASTELLA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORCABRAL','PROFESSOR CABRAL'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORCARLOS','PROFESSOR CARLOS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORCARVALHO','PROFESSOR CARVALHO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORCASTELO','PROFESSOR CASTELO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORCONSUELO','PROFESSOR CONSUELO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORCOSTA','PROFESSOR COSTA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORDEMETRIO','PROFESSOR DEMETRIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORDEMÉTRIO','PROFESSOR DEMÉTRIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORDIAS','PROFESSOR DIAS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORDOMINGOS','PROFESSOR DOMINGOS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSOREDGARD','PROFESSOR EDGARD'),
('BR-CE-Fortaleza','parcel',2,'PROFESSOREDUARDO','PROFESSOR EDUARDO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORELÁDIO','PROFESSOR ELÁDIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSOREMÍLIA','PROFESSOR EMÍLIA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSOREUCLIDES','PROFESSOR EUCLIDES'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORFRANCICO','PROFESSOR FRANCICO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORFRANCISCA','PROFESSOR FRANCISCA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORFRANCISCO','PROFESSOR FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORGERARDO','PROFESSOR GERARDO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORGLAUCO','PROFESSOR GLAUCO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORGOMES','PROFESSOR GOMES'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORGONÇALVES','PROFESSOR GONÇALVES'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORGUILHON','PROFESSOR GUILHON'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORHELOISA','PROFESSOR HELOISA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORHENRIQUE','PROFESSOR HENRIQUE'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORHERACLITO','PROFESSOR HERACLITO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORHERIBALDO','PROFESSOR HERIBALDO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORISAÍAS','PROFESSOR ISAÍAS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJACINTO','PROFESSOR JACINTO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJOAQUIM','PROFESSOR JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJOSÉ','PROFESSOR JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJOÃO','PROFESSOR JOÃO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJUCA','PROFESSOR JUCA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJURACI','PROFESSOR JURACI'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORJUREMA','PROFESSOR JUREMA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORLINO','PROFESSOR LINO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMANDUCA','PROFESSOR MANDUCA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMANOEL','PROFESSOR MANOEL'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMARCOS','PROFESSOR MARCOS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMARIETA','PROFESSOR MARIETA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMARTINS','PROFESSOR MARTINS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMIRAMAR','PROFESSOR MIRAMAR'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMIRANDA','PROFESSOR MIRANDA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMORAIS','PROFESSOR MORAIS'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMOREIRA','PROFESSOR MOREIRA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMOZART','PROFESSOR MOZART'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMURILO','PROFESSOR MURILO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORMÁRIO','PROFESSOR MÁRIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORNELSON','PROFESSOR NELSON'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORNOGUEIRA','PROFESSOR NOGUEIRA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSOROCELO','PROFESSOR OCELO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORODILIO','PROFESSOR ODILIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORODILON','PROFESSOR ODILON'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORONÉLIO','PROFESSOR ONÉLIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSOROTAVIO','PROFESSOR OTAVIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORPARENTE','PROFESSOR PARENTE'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORPAULO','PROFESSOR PAULO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORPEDRO','PROFESSOR PEDRO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORPESSOA','PROFESSOR PESSOA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORPROFETA','PROFESSOR PROFETA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORRAIMUNDA','PROFESSOR RAIMUNDA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORRAIMUNDO','PROFESSOR RAIMUNDO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORROBERTO','PROFESSOR ROBERTO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORSERRANO','PROFESSOR SERRANO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORSILA','PROFESSOR SILA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORSOLON','PROFESSOR SOLON'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORTEODORICO','PROFESSOR TEODORICO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORTITO','PROFESSOR TITO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORVALMIR','PROFESSOR VALMIR'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORVICENTE','PROFESSOR VICENTE'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORVIEIRA','PROFESSOR VIEIRA'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORVIRGÍLIO','PROFESSOR VIRGÍLIO'),
('BR-CE-Fortaleza','parcel',2,'PROFESSORWILSON','PROFESSOR WILSON'),
('BR-CE-Fortaleza','parcel',2,'RADIALISTAJOSÉ','RADIALISTA JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'RADIALISTAJOÃO','RADIALISTA JOÃO'),
('BR-CE-Fortaleza','parcel',2,'REVERENDOBOLIVAR','REVERENDO BOLIVAR'),
('BR-CE-Fortaleza','parcel',2,'REVERENDOOSMAR','REVERENDO OSMAR'),
('BR-CE-Fortaleza','parcel',2,'SANTAADÉLIA','SANTA ADÉLIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAAMÉLIA','SANTA AMÉLIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAANA','SANTA ANA'),
('BR-CE-Fortaleza','parcel',2,'SANTAAPARECIDA','SANTA APARECIDA'),
('BR-CE-Fortaleza','parcel',2,'SANTAAPOLÔNIA','SANTA APOLÔNIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAARIANE','SANTA ARIANE'),
('BR-CE-Fortaleza','parcel',2,'SANTAATRA','SANTA ATRA'),
('BR-CE-Fortaleza','parcel',2,'SANTABAIA','SANTA BAIA'),
('BR-CE-Fortaleza','parcel',2,'SANTABARBARA','SANTA BARBARA'),
('BR-CE-Fortaleza','parcel',2,'SANTABEATRIZ','SANTA BEATRIZ'),
('BR-CE-Fortaleza','parcel',2,'SANTABRANCA','SANTA BRANCA'),
('BR-CE-Fortaleza','parcel',2,'SANTACATARINA','SANTA CATARINA'),
('BR-CE-Fortaleza','parcel',2,'SANTACECILIA','SANTA CECILIA'),
('BR-CE-Fortaleza','parcel',2,'SANTACLARA','SANTA CLARA'),
('BR-CE-Fortaleza','parcel',2,'SANTACRUZ','SANTA CRUZ'),
('BR-CE-Fortaleza','parcel',2,'SANTAEDWIGENS','SANTA EDWIGENS'),
('BR-CE-Fortaleza','parcel',2,'SANTAEDWIRGENS','SANTA EDWIRGENS'),
('BR-CE-Fortaleza','parcel',2,'SANTAEDWIRGES','SANTA EDWIRGES'),
('BR-CE-Fortaleza','parcel',2,'SANTAEFIGÊNIA','SANTA EFIGÊNIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAELISA','SANTA ELISA'),
('BR-CE-Fortaleza','parcel',2,'SANTAELIZA','SANTA ELIZA'),
('BR-CE-Fortaleza','parcel',2,'SANTAESMERALDA','SANTA ESMERALDA'),
('BR-CE-Fortaleza','parcel',2,'SANTAESTELA','SANTA ESTELA'),
('BR-CE-Fortaleza','parcel',2,'SANTAFE','SANTA FE'),
('BR-CE-Fortaleza','parcel',2,'SANTAFILOMENA','SANTA FILOMENA'),
('BR-CE-Fortaleza','parcel',2,'SANTAFÉ','SANTA FÉ'),
('BR-CE-Fortaleza','parcel',2,'SANTAGERTRUDES','SANTA GERTRUDES'),
('BR-CE-Fortaleza','parcel',2,'SANTAINES','SANTA INES'),
('BR-CE-Fortaleza','parcel',2,'SANTAINÊS','SANTA INÊS'),
('BR-CE-Fortaleza','parcel',2,'SANTAISABEL','SANTA ISABEL'),
('BR-CE-Fortaleza','parcel',2,'SANTAJOANA','SANTA JOANA'),
('BR-CE-Fortaleza','parcel',2,'SANTAJULIA','SANTA JULIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAJÚLIA','SANTA JÚLIA'),
('BR-CE-Fortaleza','parcel',2,'SANTALIDUINA','SANTA LIDUINA'),
('BR-CE-Fortaleza','parcel',2,'SANTALIDUÍNA','SANTA LIDUÍNA'),
('BR-CE-Fortaleza','parcel',2,'SANTALUCIA','SANTA LUCIA'),
('BR-CE-Fortaleza','parcel',2,'SANTALUCRÉCIA','SANTA LUCRÉCIA'),
('BR-CE-Fortaleza','parcel',2,'SANTALUZIA','SANTA LUZIA'),
('BR-CE-Fortaleza','parcel',2,'SANTALÚCIA','SANTA LÚCIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAMADALENA','SANTA MADALENA'),
('BR-CE-Fortaleza','parcel',2,'SANTAMARGARIDA','SANTA MARGARIDA'),
('BR-CE-Fortaleza','parcel',2,'SANTAMARIA','SANTA MARIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAMARINA','SANTA MARINA'),
('BR-CE-Fortaleza','parcel',2,'SANTAMARTA','SANTA MARTA'),
('BR-CE-Fortaleza','parcel',2,'SANTAMÔNICA','SANTA MÔNICA'),
('BR-CE-Fortaleza','parcel',2,'SANTAPRUDÊNCIA','SANTA PRUDÊNCIA'),
('BR-CE-Fortaleza','parcel',2,'SANTAQUITÉRIA','SANTA QUITÉRIA'),
('BR-CE-Fortaleza','parcel',2,'SANTARITA','SANTA RITA'),
('BR-CE-Fortaleza','parcel',2,'SANTAROSA','SANTA ROSA'),
('BR-CE-Fortaleza','parcel',2,'SANTAROSÁLIA','SANTA ROSÁLIA'),
('BR-CE-Fortaleza','parcel',2,'SANTASOFIA','SANTA SOFIA'),
('BR-CE-Fortaleza','parcel',2,'SANTATEREZA','SANTA TEREZA'),
('BR-CE-Fortaleza','parcel',2,'SANTATEREZINHA','SANTA TEREZINHA'),
('BR-CE-Fortaleza','parcel',2,'SANTAURSULA','SANTA URSULA'),
('BR-CE-Fortaleza','parcel',2,'SANTAÂNGELA','SANTA ÂNGELA'),
('BR-CE-Fortaleza','parcel',2,'SANTOAGIMIRO','SANTO AGIMIRO'),
('BR-CE-Fortaleza','parcel',2,'SANTOAGOSTINHO','SANTO AGOSTINHO'),
('BR-CE-Fortaleza','parcel',2,'SANTOAMARO','SANTO AMARO'),
('BR-CE-Fortaleza','parcel',2,'SANTOANASTÁCIO','SANTO ANASTÁCIO'),
('BR-CE-Fortaleza','parcel',2,'SANTOANDRE','SANTO ANDRE'),
('BR-CE-Fortaleza','parcel',2,'SANTOANTONIO','SANTO ANTONIO'),
('BR-CE-Fortaleza','parcel',2,'SANTOANTÔNIO','SANTO ANTÔNIO'),
('BR-CE-Fortaleza','parcel',2,'SANTOESTEVÃO','SANTO ESTEVÃO'),
('BR-CE-Fortaleza','parcel',2,'SANTOINACIO','SANTO INACIO'),
('BR-CE-Fortaleza','parcel',2,'SANTOINÁCIO','SANTO INÁCIO'),
('BR-CE-Fortaleza','parcel',2,'SANTOTOMAZ','SANTO TOMAZ'),
('BR-CE-Fortaleza','parcel',2,'SAOBASÍLIO','SAO BASÍLIO'),
('BR-CE-Fortaleza','parcel',2,'SAOBENEDITO','SAO BENEDITO'),
('BR-CE-Fortaleza','parcel',2,'SAOBENTO','SAO BENTO'),
('BR-CE-Fortaleza','parcel',2,'SAOBERNARDO','SAO BERNARDO'),
('BR-CE-Fortaleza','parcel',2,'SAOCAETANO','SAO CAETANO'),
('BR-CE-Fortaleza','parcel',2,'SAOCAMILO','SAO CAMILO'),
('BR-CE-Fortaleza','parcel',2,'SAOCARLOS','SAO CARLOS'),
('BR-CE-Fortaleza','parcel',2,'SAOCIPRIANO','SAO CIPRIANO'),
('BR-CE-Fortaleza','parcel',2,'SAOCONRADO','SAO CONRADO'),
('BR-CE-Fortaleza','parcel',2,'SAOCONSTÂNCIO','SAO CONSTÂNCIO'),
('BR-CE-Fortaleza','parcel',2,'SAODAMIÃO','SAO DAMIÃO'),
('BR-CE-Fortaleza','parcel',2,'SAODOMINGOS','SAO DOMINGOS'),
('BR-CE-Fortaleza','parcel',2,'SAODONATO','SAO DONATO'),
('BR-CE-Fortaleza','parcel',2,'SAOFELICIANO','SAO FELICIANO'),
('BR-CE-Fortaleza','parcel',2,'SAOFELIPE','SAO FELIPE'),
('BR-CE-Fortaleza','parcel',2,'SAOFIDÉLIX','SAO FIDÉLIX'),
('BR-CE-Fortaleza','parcel',2,'SAOFRANCISCO','SAO FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'SAOFÉLIX','SAO FÉLIX'),
('BR-CE-Fortaleza','parcel',2,'SAOGABRIEL','SAO GABRIEL'),
('BR-CE-Fortaleza','parcel',2,'SAOGERARDO','SAO GERARDO'),
('BR-CE-Fortaleza','parcel',2,'SAOGONÇALO','SAO GONÇALO'),
('BR-CE-Fortaleza','parcel',2,'SAOGREGORIO','SAO GREGORIO'),
('BR-CE-Fortaleza','parcel',2,'SAOJAIRO','SAO JAIRO'),
('BR-CE-Fortaleza','parcel',2,'SAOJANUÁRIO','SAO JANUÁRIO'),
('BR-CE-Fortaleza','parcel',2,'SAOJERÔNIMO','SAO JERÔNIMO'),
('BR-CE-Fortaleza','parcel',2,'SAOJOAO','SAO JOAO'),
('BR-CE-Fortaleza','parcel',2,'SAOJORGE','SAO JORGE'),
('BR-CE-Fortaleza','parcel',2,'SAOJOSE','SAO JOSE'),
('BR-CE-Fortaleza','parcel',2,'SAOJOSÉ','SAO JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'SAOJOÃO','SAO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'SAOJUDAS','SAO JUDAS'),
('BR-CE-Fortaleza','parcel',2,'SAOLEOPOLDO','SAO LEOPOLDO'),
('BR-CE-Fortaleza','parcel',2,'SAOLONGUINHO','SAO LONGUINHO'),
('BR-CE-Fortaleza','parcel',2,'SAOLUCAS','SAO LUCAS'),
('BR-CE-Fortaleza','parcel',2,'SAOLUDOVICO','SAO LUDOVICO'),
('BR-CE-Fortaleza','parcel',2,'SAOLUIS','SAO LUIS'),
('BR-CE-Fortaleza','parcel',2,'SAOLUIZ','SAO LUIZ'),
('BR-CE-Fortaleza','parcel',2,'SAOLÁZARO','SAO LÁZARO'),
('BR-CE-Fortaleza','parcel',2,'SAOMANUEL','SAO MANUEL'),
('BR-CE-Fortaleza','parcel',2,'SAOMARCOS','SAO MARCOS'),
('BR-CE-Fortaleza','parcel',2,'SAOMARIA','SAO MARIA'),
('BR-CE-Fortaleza','parcel',2,'SAOMATEUS','SAO MATEUS'),
('BR-CE-Fortaleza','parcel',2,'SAOMAURICIO','SAO MAURICIO'),
('BR-CE-Fortaleza','parcel',2,'SAOMIGUEL','SAO MIGUEL'),
('BR-CE-Fortaleza','parcel',2,'SAOPANTALEAO','SAO PANTALEAO'),
('BR-CE-Fortaleza','parcel',2,'SAOPAULO','SAO PAULO'),
('BR-CE-Fortaleza','parcel',2,'SAOPEDRO','SAO PEDRO'),
('BR-CE-Fortaleza','parcel',2,'SAORAIMUNDO','SAO RAIMUNDO'),
('BR-CE-Fortaleza','parcel',2,'SAOROQUE','SAO ROQUE'),
('BR-CE-Fortaleza','parcel',2,'SAOSEBASTIAO','SAO SEBASTIAO'),
('BR-CE-Fortaleza','parcel',2,'SAOSEBASTIÃO','SAO SEBASTIÃO'),
('BR-CE-Fortaleza','parcel',2,'SAOSEBASTÃO','SAO SEBASTÃO'),
('BR-CE-Fortaleza','parcel',2,'SAOTEMÓTEO','SAO TEMÓTEO'),
('BR-CE-Fortaleza','parcel',2,'SAOTOMAS','SAO TOMAS'),
('BR-CE-Fortaleza','parcel',2,'SAOTOME','SAO TOME'),
('BR-CE-Fortaleza','parcel',2,'SAOTURIBIO','SAO TURIBIO'),
('BR-CE-Fortaleza','parcel',2,'SAOVICENTE','SAO VICENTE'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOBARBOSA','SARGENTO BARBOSA'),
('BR-CE-Fortaleza','parcel',2,'SARGENTODOMINGOS','SARGENTO DOMINGOS'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOEXPEDITO','SARGENTO EXPEDITO'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOHERMÍNIO','SARGENTO HERMÍNIO'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOJOSÉ','SARGENTO JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOJOÃO','SARGENTO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'SARGENTONERI','SARGENTO NERI'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOPORTUGAL','SARGENTO PORTUGAL'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOSERPA','SARGENTO SERPA'),
('BR-CE-Fortaleza','parcel',2,'SARGENTOSILVA','SARGENTO SILVA'),
('BR-CE-Fortaleza','parcel',2,'SENADORALENCAR','SENADOR ALENCAR'),
('BR-CE-Fortaleza','parcel',2,'SENADORALMINO','SENADOR ALMINO'),
('BR-CE-Fortaleza','parcel',2,'SENADORALMIR','SENADOR ALMIR'),
('BR-CE-Fortaleza','parcel',2,'SENADORCARLOS','SENADOR CARLOS'),
('BR-CE-Fortaleza','parcel',2,'SENADORCATUNDA','SENADOR CATUNDA'),
('BR-CE-Fortaleza','parcel',2,'SENADORFERNANDES','SENADOR FERNANDES'),
('BR-CE-Fortaleza','parcel',2,'SENADORJAGUARIBE','SENADOR JAGUARIBE'),
('BR-CE-Fortaleza','parcel',2,'SENADORMACHADO','SENADOR MACHADO'),
('BR-CE-Fortaleza','parcel',2,'SENADORMILTON','SENADOR MILTON'),
('BR-CE-Fortaleza','parcel',2,'SENADORPAULA','SENADOR PAULA'),
('BR-CE-Fortaleza','parcel',2,'SENADORPOMPEU','SENADOR POMPEU'),
('BR-CE-Fortaleza','parcel',2,'SENADORROBERT','SENADOR ROBERT'),
('BR-CE-Fortaleza','parcel',2,'SENADORSÁ','SENADOR SÁ'),
('BR-CE-Fortaleza','parcel',2,'SENADORVIRGÍLIO','SENADOR VIRGÍLIO'),
('BR-CE-Fortaleza','parcel',2,'SENADORÁLVARO','SENADOR ÁLVARO'),
('BR-CE-Fortaleza','parcel',2,'SENHORA SANTANA','SENHORA SANTANA'),
('BR-CE-Fortaleza','parcel',2,'TABELIAOCARLOTO','TABELIAO CARLOTO'),
('BR-CE-Fortaleza','parcel',2,'TABELIAOFABIÃO','TABELIAO FABIÃO'),
('BR-CE-Fortaleza','parcel',2,'TABELIAOJOAQUIM','TABELIAO JOAQUIM'),
('BR-CE-Fortaleza','parcel',2,'TABELIAOJOÃO','TABELIAO JOÃO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEAMARANTE','TENENTE AMARANTE'),
('BR-CE-Fortaleza','parcel',2,'TENENTEAMAURÍ','TENENTE AMAURÍ'),
('BR-CE-Fortaleza','parcel',2,'TENENTEANDERSON','TENENTE ANDERSON'),
('BR-CE-Fortaleza','parcel',2,'TENENTEAURÉLIO','TENENTE AURÉLIO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEBARBOSA','TENENTE BARBOSA'),
('BR-CE-Fortaleza','parcel',2,'TENENTEBENÉVOLO','TENENTE BENÉVOLO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEBEZERRA','TENENTE BEZERRA'),
('BR-CE-Fortaleza','parcel',2,'TENENTEBOTELHO','TENENTE BOTELHO'),
('BR-CE-Fortaleza','parcel',2,'TENENTECORONEL','TENENTE CORONEL'),
('BR-CE-Fortaleza','parcel',2,'TENENTECOSTA','TENENTE COSTA'),
('BR-CE-Fortaleza','parcel',2,'TENENTEELIEZER','TENENTE ELIEZER'),
('BR-CE-Fortaleza','parcel',2,'TENENTEFRANCISCO','TENENTE FRANCISCO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEJAIME','TENENTE JAIME'),
('BR-CE-Fortaleza','parcel',2,'TENENTEJONAS','TENENTE JONAS'),
('BR-CE-Fortaleza','parcel',2,'TENENTEJOSÉ','TENENTE JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'TENENTEJOÃO','TENENTE JOÃO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEJURANDIR','TENENTE JURANDIR'),
('BR-CE-Fortaleza','parcel',2,'TENENTELAURO','TENENTE LAURO'),
('BR-CE-Fortaleza','parcel',2,'TENENTELIRA','TENENTE LIRA'),
('BR-CE-Fortaleza','parcel',2,'TENENTELISBOA','TENENTE LISBOA'),
('BR-CE-Fortaleza','parcel',2,'TENENTELOURIVAL','TENENTE LOURIVAL'),
('BR-CE-Fortaleza','parcel',2,'TENENTEMARCOS','TENENTE MARCOS'),
('BR-CE-Fortaleza','parcel',2,'TENENTEMARQUES','TENENTE MARQUES'),
('BR-CE-Fortaleza','parcel',2,'TENENTEMATIAS','TENENTE MATIAS'),
('BR-CE-Fortaleza','parcel',2,'TENENTEMOACIR','TENENTE MOACIR'),
('BR-CE-Fortaleza','parcel',2,'TENENTEMONTEIRO','TENENTE MONTEIRO'),
('BR-CE-Fortaleza','parcel',2,'TENENTENAPOLEÃO','TENENTE NAPOLEÃO'),
('BR-CE-Fortaleza','parcel',2,'TENENTENICOLAU','TENENTE NICOLAU'),
('BR-CE-Fortaleza','parcel',2,'TENENTEQUEIROZ','TENENTE QUEIROZ'),
('BR-CE-Fortaleza','parcel',2,'TENENTEQUEIRÓS','TENENTE QUEIRÓS'),
('BR-CE-Fortaleza','parcel',2,'TENENTERENATO','TENENTE RENATO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEROMA','TENENTE ROMA'),
('BR-CE-Fortaleza','parcel',2,'TENENTETITO','TENENTE TITO'),
('BR-CE-Fortaleza','parcel',2,'TENENTEVIENA','TENENTE VIENA'),
('BR-CE-Fortaleza','parcel',2,'TENENTEWILSON','TENENTE WILSON'),
('BR-CE-Fortaleza','parcel',2,'TIPOGRAFOSALES','TIPOGRAFO SALES'),
('BR-CE-Fortaleza','parcel',2,'TOPOGRÁFOSALES','TOPOGRÁFO SALES'),
('BR-CE-Fortaleza','parcel',2,'VEREADORADEMAR','VEREADOR ADEMAR'),
('BR-CE-Fortaleza','parcel',2,'VEREADORJOSÉ','VEREADOR JOSÉ'),
('BR-CE-Fortaleza','parcel',2,'VEREADORLALINHA','VEREADOR LALINHA'),
('BR-CE-Fortaleza','parcel',2,'VEREADOROTONI','VEREADOR OTONI'),
('BR-CE-Fortaleza','parcel',2,'VEREADORPAULO','VEREADOR PAULO'),
('BR-CE-Fortaleza','parcel',2,'VEREADORPEDRO','VEREADOR PEDRO'),
('BR-CE-Fortaleza','parcel',2,'VEREADORS','VEREADOR S'),
('BR-CE-Fortaleza','parcel',2,'VEREADORZÉLIA','VEREADOR ZÉLIA'),
('BR-CE-Fortaleza','parcel',2,'VIOLEIROADERALDO','VIOLEIRO ADERALDO'),
('BR-CE-Fortaleza','parcel',2,'VISCONDEBARBACENA','VISCONDE BARBACENA'),
('BR-CE-Fortaleza','parcel',2,'VISCONDECAIRU','VISCONDE CAIRU'),
('BR-CE-Fortaleza','parcel',2,'VISCONDEDA','VISCONDE DA'),
('BR-CE-Fortaleza','parcel',2,'VISCONDEDE','VISCONDE DE'),
('BR-CE-Fortaleza','parcel',2,'VISCONDEDO','VISCONDE DO'),
('BR-CE-Fortaleza','parcel',2,'VISCONDEPELOTAS','VISCONDE PELOTAS'),

('BR-CE-Fortaleza','parcel',3,'(CJ','(Conjunto'),
('BR-CE-Fortaleza','parcel',3,'(CONJ','(Conjunto'),
('BR-CE-Fortaleza','parcel',3,'(CONJ.','(Conjunto'),
('BR-CE-Fortaleza','parcel',3,'(CONJ.ESPERANÇA)','(Conjunto ESPERANÇA)'),
('BR-CE-Fortaleza','parcel',3,'(CONJ.GUAJERU)','(ConjuntoGUAJERU)'),
('BR-CE-Fortaleza','parcel',3,'(CONJ.RESID.','(Conjunto Residencial'),
('BR-CE-Fortaleza','parcel',3,'(CONJ.RESID.PEQUENO','(Conjunto Residencial PEQUENO'),
('BR-CE-Fortaleza','parcel',3,'(Cj','(Conjunto'),
('BR-CE-Fortaleza','parcel',3,'(LOT','(Loteamento'),
('BR-CE-Fortaleza','parcel',3,'(LOT.','(Loteamento'),
-- ('BR-CE-Fortaleza','parcel',3,'(LT',''),
('BR-CE-Fortaleza','parcel',3,'(Lot','(Loteamento'),
('BR-CE-Fortaleza','parcel',3,'(RES','(Residencial'),
('BR-CE-Fortaleza','parcel',3,'(RESID.','(Residencial'),
('BR-CE-Fortaleza','parcel',3,'(RESID.BOA','(Residencial BOA'),
('BR-CE-Fortaleza','parcel',3,'DUMAR()','DUMAR'),
('BR-CE-Fortaleza','parcel',3,'ESPERANÇA(GENIBAÚ)','ESPERANÇA (GENIBAÚ)'),
('BR-CE-Fortaleza','parcel',3,'MADEIRA(FLORESTA)','MADEIRA (FLORESTA)'),
('BR-CE-Fortaleza','parcel',3,'NOGUEIRA(PRESIDENTE','NOGUEIRA (PRESIDENTE'),
('BR-CE-Fortaleza','parcel',3,'SENHORAAPARECIDA','SENHORA APARECIDA'),
('BR-CE-Fortaleza','parcel',3,'SENHORADA','SENHORA DA'),
('BR-CE-Fortaleza','parcel',3,'SENHORADAS','SENHORA DAS'),
('BR-CE-Fortaleza','parcel',3,'SENHORADE','SENHORA DE'),
('BR-CE-Fortaleza','parcel',3,'SENHORADO','SENHORA DO'),
('BR-CE-Fortaleza','parcel',3,'SENHORADOS','SENHORA DOS'),

('BR-CE-Fortaleza','parcel',4,'(CONJ','(Conjunto'),
('BR-CE-Fortaleza','parcel',4,'(CONJ.','(Conjunto'),
('BR-CE-Fortaleza','parcel',4,'LOT','Loteamento'),
('BR-CE-Fortaleza','parcel',4,'LOT.','Loteamento'),
('BR-CE-Fortaleza','parcel',4,'RES','Residencial'),
('BR-CE-Fortaleza','parcel',4,'RES.','Residencial'),
('BR-CE-Fortaleza','parcel',4,'RESD','Residencial'),
('BR-CE-Fortaleza','parcel',4,'RESID.','Residencial'),
('BR-CE-Fortaleza','parcel',4,'RESID.CURIÓ)','Residencial Curió)'),

('BR-MG-BeloHorizonte','geoaddress',1,'ACS.','Acesso'),
('BR-MG-BeloHorizonte','geoaddress',1,'ALA.','Alameda'),
('BR-MG-BeloHorizonte','geoaddress',1,'AVE.','Avenida'),
('BR-MG-BeloHorizonte','geoaddress',1,'BEC.','Beco'),
('BR-MG-BeloHorizonte','geoaddress',1,'ELP.','Espaço Livre para Pedestre'),
('BR-MG-BeloHorizonte','geoaddress',1,'EST.','Estrada'),
('BR-MG-BeloHorizonte','geoaddress',1,'LRG.','Largo'),
('BR-MG-BeloHorizonte','geoaddress',1,'PCA.','Praça'),
('BR-MG-BeloHorizonte','geoaddress',1,'RDP.','Rua de Pedestre'),
('BR-MG-BeloHorizonte','geoaddress',1,'ROD.','Rodovia'),
('BR-MG-BeloHorizonte','geoaddress',1,'TRE.','Trevo'),
('BR-MG-BeloHorizonte','geoaddress',1,'TRI.','Trincheira'),
('BR-MG-BeloHorizonte','geoaddress',1,'TRV.','Travessa'),
('BR-MG-BeloHorizonte','geoaddress',1,'VDP.','Via de Pedestre'),
('BR-MG-BeloHorizonte','geoaddress',1,'VDT.','Viaduto')

) AS t (isolabel_ext,layer,field,abbrev,nabrrev)
;
