
DROP TABLE abbrevconsolidado;
CREATE TABLE abbrevconsolidado AS
SELECT isolabel_ext, layer, field, abbrev, nabrrev
FROM
(
    VALUES
    ('BR-MG-Contagem','via',1,'ALA','Alameda'),
    ('BR-MG-Contagem','via',1,'Av.','Avenida'),
    ('BR-MG-Contagem','via',1,'Bec','Beco'),
    ('BR-MG-Contagem','via',1,'Est.','Estrada'),
    ('BR-MG-Contagem','via',1,'Pca.','Praça'),
    ('BR-MG-Contagem','via',1,'Pça.','Praça'),
    ('BR-MG-Contagem','via',1,'R\ua','Rua'),
    ('BR-MG-Contagem','via',1,'Rod.','Rodovia'),
    ('BR-MG-Contagem','via',1,'Trv','Travessa'),
    ('BR-MG-Contagem','via',1,'Trv.','Travessa'),
    ('BR-MG-Contagem','via',1,'Tvr.','Travessa'),
    ('BR-MG-Contagem','via',6,'Sra.','Senhora'),
    ('BR-MG-Contagem','via',2,'BEM-TE-VI','Bem-te-vi'),
    -- ('BR-MG-Contagem','via',1,'S.JOSE',''),
    ('BR-MG-Contagem','geoaddress',1,'Ala','Alameda'),
    ('BR-MG-Contagem','geoaddress',1,'Av.','Avenida'),
    ('BR-MG-Contagem','geoaddress',1,'Bec','Beco'),
    ('BR-MG-Contagem','geoaddress',1,'Est.','Estrada'),
    ('BR-MG-Contagem','geoaddress',1,'Pca','Praça'),
    ('BR-MG-Contagem','geoaddress',1,'Rod.','Rodovia'),
    ('BR-MG-Contagem','geoaddress',1,'Trv','Travessa'),
    ('BR-MG-Contagem','geoaddress',2,'1.','1'),
    ('BR-MG-Contagem','geoaddress',2,'CAP.','Capitão'),
    ('BR-MG-Contagem','geoaddress',2,'CEL','Coronel'),
    ('BR-MG-Contagem','geoaddress',2,'CEL.','Coronel'),
    ('BR-MG-Contagem','geoaddress',2,'GAL','General'),
    ('BR-MG-Contagem','geoaddress',2,'GAL.','General'),
    ('BR-MG-Contagem','geoaddress',2,'DR','Doutor'),
    ('BR-MG-Contagem','geoaddress',2,'DR.','Doutor'),
    ('BR-MG-Contagem','geoaddress',2,'Dr','Doutor'),
    ('BR-MG-Contagem','geoaddress',2,'ESP.','Expedicionário'),
    ('BR-MG-Contagem','geoaddress',2,'PROF.','Professor'),
    ('BR-MG-Contagem','geoaddress',2,'SARG.','Sargento'),
    ('BR-MG-Contagem','geoaddress',3,'(Cj','(Conjunto'),
    ('BR-MG-Contagem','geoaddress',2,'VER.','Vereador'),
    ('BR-MG-Contagem','geoaddress',2,'DEP.','Deputado'),
    ('BR-MG-Contagem','geoaddress',2,'DES.','Desembargador'),
    ('BR-MG-Contagem','geoaddress',3,'(THEREZINHA','(Therezinha'),
    ('BR-MG-Contagem','geoaddress',5,'"A"','A'),
    ('BR-MG-Contagem','geoaddress',4,'D''AVIL','D''Ávila'),
    ('BR-MG-Contagem','geoaddress',4,'DAVILA','D''Ávila'),
    ('BR-MG-Contagem','geoaddress',3,'D.AGUA','D''Água')
    -- ('BR-MG-Contagem','geoaddress',3,'A.PASCOALINE','Alberto Pascoaline'),
    -- ('BR-MG-Contagem','geoaddress',3,'Ant.Guido','Antônio Guido'),
    -- ('BR-MG-Contagem','geoaddress',2,'B.H.','Belo Horizonte'),

    ('BR-MG-Contagem','parcel',1,'CONJ.','Conjunto'),
    ('BR-MG-Contagem','parcel',2,'HAB.','Habitacional'),
    ('BR-MG-Contagem','parcel',3,'VER.','Vereador'),
    ('BR-SP-Jundiai','geoaddress',1,'AL','Alameda'),
    ('BR-SP-Jundiai','geoaddress',1,'AV','Avenida'),
    -- ('BR-SP-Jundiai','geoaddress',1,'CM',''),
    ('BR-SP-Jundiai','geoaddress',1,'ET','Estrada'),
    ('BR-SP-Jundiai','geoaddress',1,'PC','Praça'),
    ('BR-SP-Jundiai','geoaddress',1,'R','Rua'),
    ('BR-SP-Jundiai','geoaddress',1,'RD','Rodovia'),
    ('BR-SP-Jundiai','geoaddress',1,'TV','Travessa'),
    ('BR-SP-Jundiai','geoaddress',1,'V','Via'),
    ('BR-SP-Jundiai','geoaddress',1,'VD','Viaduto'),
    ('BR-SP-Jundiai','geoaddress',1,'VL','Vila'),
    -- ('BR-SP-Jundiai','geoaddress',1,'VP',''),
    ('BR-SP-Jundiai','geoaddress',2,'DR','Doutor'),
    ('BR-SP-Jundiai','geoaddress',2,'PRFA','Professora'),
    ('BR-SP-Jundiai','geoaddress',2,'PROF','Professor'),
    ('BR-SP-Jundiai','geoaddress',2,'PREB','Presbítero'),
    ('BR-SP-Jundiai','geoaddress',2,'PROLONG','Prolongamento'),
    ('BR-SP-Jundiai','geoaddress',2,'STA','Santa'),
    ('BR-SP-Jundiai','geoaddress',2,'SOR','Soror'),
    ('BR-SP-Jundiai','geoaddress',2,'VER','Vereador'),
    ('BR-SP-Jundiai','geoaddress',2,'CAP','Capitão'),
    ('BR-SP-Jundiai','geoaddress',2,'CB','Cabo'),
    ('BR-SP-Jundiai','geoaddress',2,'CDE','Conde'),
    ('BR-SP-Jundiai','geoaddress',2,'CDOR','Comendador'),
    ('BR-SP-Jundiai','geoaddress',2,'CEL','Coronel'),
    ('BR-SP-Jundiai','geoaddress',2,'DIAC','Diácomo'),
    ('BR-SP-Jundiai','geoaddress',2,'DRA','Doutora'),
    ('BR-SP-Jundiai','geoaddress',2,'ENG','Engenheiro'),
    ('BR-SP-Jundiai','geoaddress',2,'EVA','Evangelista'),
    ('BR-SP-Jundiai','geoaddress',2,'FR','Frei'),
    ('BR-SP-Jundiai','geoaddress',2,'GEN','General'),
    ('BR-SP-Jundiai','geoaddress',2,'MAJ','Major'),
    ('BR-SP-Jundiai','geoaddress',2,'MI','Missionário'),
    ('BR-SP-Jundiai','geoaddress',2,'MIN','Ministro'),
    ('BR-SP-Jundiai','geoaddress',2,'MON','Monsenhor'),
    ('BR-SP-Jundiai','geoaddress',2,'MTRO','Maestro'),
    ('BR-SP-Jundiai','geoaddress',2,'PA','Pastor'),
    ('BR-SP-Jundiai','geoaddress',2,'PE','Padre'),
    ('BR-SP-Jundiai','geoaddress',2,'PRSA','Princesa'),
    ('BR-SP-Jundiai','geoaddress',2,'S/DENOMINAÇÃO','Sem denominação'),
    ('BR-SP-Jundiai','geoaddress',2,'SGT','Sargento'),
    ('BR-SP-Jundiai','geoaddress',2,'STA','Santa'),
    ('BR-SP-Jundiai','geoaddress',2,'STO','Santo'),
    ('BR-SP-Jundiai','geoaddress',2,'TEN','Tenente'),
    ('BR-SP-Jundiai','geoaddress',2,'VER','Vereador'),
    ('BR-SP-Jundiai','geoaddress',2,'VIG','Vigário'),
    ('BR-SP-Jundiai','geoaddress',2,'VISC','Visconde'),
    ('BR-SP-Jundiai','geoaddress',2,'PRES','Presidente'),
    ('BR-SP-Jundiai','geoaddress',2,'CMTE','Comandante'),

    ('BR-SP-Jundiai','geoaddress',2,'BRANCA/S.INDUS.','Branca/Setor Industrial'),
    ('BR-SP-Jundiai','geoaddress',1,'JD','Jardim'),
    ('BR-SP-Jundiai','geoaddress',1,'JD.SANTA','Jardim Santa'),

    ('BR-SP-Jundiai','via',1,'AC','Acesso'),
    ('BR-SP-Jundiai','via',1,'AL','Alameda'),
    ('BR-SP-Jundiai','via',1,'AV','Avenida'),
    -- ('BR-SP-Jundiai','via',1,'CM',''),
    ('BR-SP-Jundiai','via',1,'ET','Estrada'),
    ('BR-SP-Jundiai','via',1,'PC','Praça'),
    -- ('BR-SP-Jundiai','via',1,'PL',''),
    ('BR-SP-Jundiai','via',1,'PT','Ponte'),
    ('BR-SP-Jundiai','via',1,'R','Rua'),
    ('BR-SP-Jundiai','via',1,'RD','Rodovia'),
    ('BR-SP-Jundiai','via',1,'TU','Túnel'),
    ('BR-SP-Jundiai','via',1,'TV','Travessa'),
    ('BR-SP-Jundiai','via',1,'V','Via'),
    ('BR-SP-Jundiai','via',1,'VD','Viaduto'),
    ('BR-SP-Jundiai','via',1,'VL','Vila'),
    -- ('BR-SP-Jundiai','via',1,'VP',''),

    ('BR-SP-Jundiai','via',2,'CAP','Capitão'),
    ('BR-SP-Jundiai','via',2,'CB','Cabo'),
    ('BR-SP-Jundiai','via',2,'CDE','Conde'),
    ('BR-SP-Jundiai','via',2,'CDOR','Comendador'),
    ('BR-SP-Jundiai','via',2,'CEL','Coronel'),
    ('BR-SP-Jundiai','via',2,'CMTE','Comandante'),
    ('BR-SP-Jundiai','via',2,'DIAC','Diácomo'),
    ('BR-SP-Jundiai','via',2,'DR','Doutor'),
    ('BR-SP-Jundiai','via',2,'DRA','Doutora'),
    ('BR-SP-Jundiai','via',2,'ENG','Engenheiro'),
    ('BR-SP-Jundiai','via',2,'EVA','Evangelista'),
    ('BR-SP-Jundiai','via',2,'FR','Frei'),
    ('BR-SP-Jundiai','via',2,'GEN','General'),
    ('BR-SP-Jundiai','via',2,'MAJ','Major'),
    ('BR-SP-Jundiai','via',2,'MAL','Marechal'),
    ('BR-SP-Jundiai','via',2,'MI','Missionário'),
    ('BR-SP-Jundiai','via',2,'MIN','Ministro'),
    ('BR-SP-Jundiai','via',2,'MON','Monsenhor'),
    ('BR-SP-Jundiai','via',2,'MONS','Monsenhor'),
    ('BR-SP-Jundiai','via',2,'MQ','Marquês'),
    ('BR-SP-Jundiai','via',2,'MTRO','Maestro'),
    ('BR-SP-Jundiai','via',2,'PA','Pastor'),
    ('BR-SP-Jundiai','via',2,'PE','Padre'),
    ('BR-SP-Jundiai','via',2,'PM','Policial Militar'),
    ('BR-SP-Jundiai','via',2,'PREB','Presbítero'),
    ('BR-SP-Jundiai','via',2,'PRES','Presidente'),
    ('BR-SP-Jundiai','via',2,'PRFA','Professora'),
    ('BR-SP-Jundiai','via',2,'PROF','Professor'),
    ('BR-SP-Jundiai','via',2,'PREF','Prefeito'),
    ('BR-SP-Jundiai','via',2,'PROLONG','Prolongamento'),
    ('BR-SP-Jundiai','via',2,'PRSA','Princesa'),
    ('BR-SP-Jundiai','via',2,'S/DENOMINAÇÃO','Sem denominação'),
    ('BR-SP-Jundiai','via',2,'SEN','Senador'),
    ('BR-SP-Jundiai','via',2,'SGT','Sargento'),
    ('BR-SP-Jundiai','via',2,'SOR','Soror'),
    ('BR-SP-Jundiai','via',2,'STA','Santa'),
    ('BR-SP-Jundiai','via',2,'STA','Santa'),
    ('BR-SP-Jundiai','via',2,'STO','Santo'),
    ('BR-SP-Jundiai','via',2,'TEN','Tenente'),
    ('BR-SP-Jundiai','via',2,'VER','Vereador'),
    ('BR-SP-Jundiai','via',2,'VER','Vereador'),
    ('BR-SP-Jundiai','via',2,'VIG','Vigário'),
    ('BR-SP-Jundiai','via',2,'VISC','Visconde'),
    ('BR-SP-Jundiai','via',2,'PART','Particular'),
    ('BR-SP-Jundiai','via',2,'PROJ','Projetada'),

    ('BR-SP-Jundiai','via',3,'JD','Jardim'),
    ('BR-SP-Jundiai','via',3,'(Jd','(Jardim'),
    ('BR-SP-Jundiai','via',3,'LT.','Loteamento'),
    ('BR-SP-Jundiai','via',3,'RES','Residencial'),
    ('BR-SP-Jundiai','via',3,'R','Rua')
) AS t (isolabel_ext,layer,field,abbrev,nabrrev)
;
