DROP TABLE abbrevdicio;
CREATE TABLE abbrevdicio AS
SELECT isolabel_ext, old, new
FROM
(
VALUES
('BR-MG-Contagem','Alameda Alameda dos Judiciarios','Alameda Alameda dos Judiciários'),
('BR-MG-Contagem','Alameda das Acacias','Alameda das Acácias'),
('BR-MG-Contagem','Alameda das Azaleias','Alameda das Azaléias'),
('BR-MG-Contagem','Alameda das Orquideas','Alameda das Orquídeas'),
('BR-MG-Contagem','Alameda dos Anturios','Alameda dos Antúrios'),
('BR-MG-Contagem','Alameda dos Canarios','Alameda dos Canários'),
('BR-MG-Contagem','Alameda dos Girassois','Alameda dos Girassóis'),
('BR-MG-Contagem','Alameda dos Judiciarios','Alameda dos Judiciários'),
('BR-MG-Contagem','Alameda dos Medicos','Alameda dos Médicos'),
('BR-MG-Contagem','Alameda dos Veterinarios','Alameda dos Veterinários'),
('BR-MG-Contagem','Avenida Abilio Machado','Avenida Abílio Machado'),
('BR-MG-Contagem','Avenida Adutora Varzea das Flores','Avenida Adutora Várzea das Flores'),
('BR-MG-Contagem','Avenida Agua Branca','Avenida Água Branca'),
('BR-MG-Contagem','Avenida Aguas Marinhas','Avenida Águas Marinhas'),
('BR-MG-Contagem','Avenida Alvaro dos Santos','Avenida Álvaro dos Santos'),
('BR-MG-Contagem','Avenida Anibal de Macedo','Avenida Aníbal de Macedo'),
('BR-MG-Contagem','Avenida Antonio Chagas Diniz','Avenida Antônio Chagas Diniz'),
('BR-MG-Contagem','Avenida Antonio Dias','Avenida Antônio Dias'),
('BR-MG-Contagem','Avenida Antonio Jose da Rocha','Avenida Antônio José da Rocha'),
('BR-MG-Contagem','Avenida Antonio dos Santos Cabral','Avenida Antônio dos Santos Cabral'),
('BR-MG-Contagem','Avenida Braz Julio de Oliveira','Avenida Braz Júlio de Oliveira'),
('BR-MG-Contagem','Avenida Cardeal Eugenio Pacelli','Avenida Cardeal Eugênio Pacelli'),
('BR-MG-Contagem','Avenida Cesar Augusto Faria Simoes','Avenida César Augusto Faria Simões'),
('BR-MG-Contagem','Avenida Columbia','Avenida Colúmbia'),
('BR-MG-Contagem','Avenida Coronel Benjamim Guimaraes','Avenida Coronel Benjamim Guimarães'),
('BR-MG-Contagem','Avenida Dilson de Oliveira','Avenida Dílson de Oliveira'),
('BR-MG-Contagem','Avenida Emir Antonio Diniz','Avenida Emir Antônio Diniz'),
('BR-MG-Contagem','Avenida Fernao Dias','Avenida Fernão Dias'),
('BR-MG-Contagem','Avenida Imbirucu','Avenida Imbiruçu'),
('BR-MG-Contagem','Avenida Integracao','Avenida Integração'),
('BR-MG-Contagem','Avenida Joao Cesar de Oliveira','Avenida João César de Oliveira'),
('BR-MG-Contagem','Avenida Joao Gomes','Avenida João Gomes'),
('BR-MG-Contagem','Avenida Joao Gomes Cardoso','Avenida João Gomes Cardoso'),
('BR-MG-Contagem','Avenida Joao Goncalves Lima','Avenida João Gonçalves Lima'),
('BR-MG-Contagem','Avenida Joao de Deus Costa','Avenida João de Deus Costa'),
('BR-MG-Contagem','Avenida Jose Diniz e Silva','Avenida José Diniz e Silva'),
('BR-MG-Contagem','Avenida Jose Faria da Rocha','Avenida José Faria da Rocha'),
('BR-MG-Contagem','Avenida Jose Luiz da Cunha','Avenida José Luiz da Cunha'),
('BR-MG-Contagem','Avenida Jose dos Santos Diniz','Avenida José dos Santos Diniz'),
('BR-MG-Contagem','Avenida Marco Aurelio Rabelo','Avenida Marco Aurélio Rabelo'),
('BR-MG-Contagem','Avenida Maria da Gloria','Avenida Maria da Glória'),
('BR-MG-Contagem','Avenida Maria da Gloria Rocha','Avenida Maria da Glória Rocha'),
('BR-MG-Contagem','Avenida Mario Pinheiro Souza','Avenida Mário Pinheiro Souza'),
('BR-MG-Contagem','Avenida Nossa Senhora da Conceicao','Avenida Nossa Senhora da Conceição'),
('BR-MG-Contagem','Avenida Olimpio Garcia','Avenida Olímpio Garcia'),
('BR-MG-Contagem','Avenida Pedro Olimpio da Fonseca','Avenida Pedro Olímpio da Fonseca'),
('BR-MG-Contagem','Avenida Prefeito Evaristo Belem','Avenida Prefeito Evaristo Belém'),
('BR-MG-Contagem','Avenida Rio Sao Francisco','Avenida Rio São Francisco'),
('BR-MG-Contagem','Avenida Sanitaria','Avenida Sanitária'),
('BR-MG-Contagem','Avenida Sao Joao','Avenida São João'),
('BR-MG-Contagem','Avenida Tapajos','Avenida Tapajós'),
('BR-MG-Contagem','Avenida Teleferico','Avenida Teleférico'),
('BR-MG-Contagem','Avenida Tito Fulgencio','Avenida Tito Fulgêncio'),
('BR-MG-Contagem','Avenida Tres','Avenida Três'),
('BR-MG-Contagem','Avenida Via Gastao Camargos','Avenida Via Gastão Camargos'),
('BR-MG-Contagem','Avenida Via Socrates Mariani Biten','Avenida Via Sócrates Mariani Biten'),
('BR-MG-Contagem','Avenida Vicente Bufalo','Avenida Vicente Búfalo'),
('BR-MG-Contagem','Avenida Virginia Graciosi Pacelli','Avenida Virgínia Graciosi Pacelli'),
('BR-MG-Contagem','Avenida das Acacias','Avenida das Acácias'),
('BR-MG-Contagem','Avenida das Americas','Avenida das Américas'),
('BR-MG-Contagem','Praça Antonio Mourao Guimaraes','Praça Antônio Mourão Guimarães'),
('BR-MG-Contagem','Praça Farmaceutico Joao da Rocha','Praça Farmacêutico João da Rocha'),
('BR-MG-Contagem','Praça Itajai','Praça Itajaí'),
('BR-MG-Contagem','Praça Jose Olinto Fontes','Praça José Olinto Fontes'),
('BR-MG-Contagem','Praça Marilia de Dirceu','Praça Marília de Dirceu'),
('BR-MG-Contagem','Praça Nossa Senhora da Conceicao','Praça Nossa Senhora da Conceição'),
('BR-MG-Contagem','Praça Nossa Senhora da Gloria','Praça Nossa Senhora da Glória'),
('BR-MG-Contagem','Praça Nossa Senhora de Fatima','Praça Nossa Senhora de Fátima'),
('BR-MG-Contagem','Praça Sao Goncalo','Praça São Gonçalo'),
('BR-MG-Contagem','Praça Sao Jose Operario','Praça São José Operário'),
('BR-MG-Contagem','Praça Silviano Brandao','Praça Silviano Brandão'),
('BR-MG-Contagem','Rodovia Fernao Dias','Rodovia Fernão Dias'),
('BR-MG-Contagem','Rua Abaete','Rua Abaeté'),
('BR-MG-Contagem','Rua Abare','Rua Abaré'),
('BR-MG-Contagem','Rua Abraao Evangelista Diniz','Rua Abraão Evangelista Diniz'),
('BR-MG-Contagem','Rua Acacias','Rua Acácias'),
('BR-MG-Contagem','Rua Acara','Rua Acará'),
('BR-MG-Contagem','Rua Adao Sabino da Silva','Rua Adão Sabino da Silva'),
('BR-MG-Contagem','Rua Adelia Lobato','Rua Adélia Lobato'),
('BR-MG-Contagem','Rua Adutora Varzea das Flores','Rua Adutora Várzea das Flores'),
('BR-MG-Contagem','Rua Agata','Rua Ágata'),
('BR-MG-Contagem','Rua Agua Branca','Rua Água Branca'),
('BR-MG-Contagem','Rua Aguas Marinha','Rua Águas Marinha'),
('BR-MG-Contagem','Rua Aguas Marinhas','Rua Águas Marinhas'),
('BR-MG-Contagem','Rua Alameda das Aguias','Rua Alameda das Águias'),
('BR-MG-Contagem','Rua Alameda das Garcas','Rua Alameda das Garças'),
('BR-MG-Contagem','Rua Alameda dos Judiciarios','Rua Alameda dos Judiciários'),
('BR-MG-Contagem','Rua Alameda dos Rodoviarios','Rua Alameda dos Rodoviários'),
('BR-MG-Contagem','Rua Alameda dos Rouxinois','Rua Alameda dos Rouxinóis'),
('BR-MG-Contagem','Rua Alameda dos Sabias','Rua Alameda dos Sabiás'),
('BR-MG-Contagem','Rua Alcatrao','Rua Alcatrão'),
('BR-MG-Contagem','Rua Alfredo Goncalves','Rua Alfredo Gonçalves'),
('BR-MG-Contagem','Rua Alzemar Ozorio da Siva','Rua Alzemar Ozório da Siva'),
('BR-MG-Contagem','Rua Amapa','Rua Amapá'),
('BR-MG-Contagem','Rua Amelia Teixeira','Rua Amélia Teixeira'),
('BR-MG-Contagem','Rua America do Sul','Rua América do Sul'),
('BR-MG-Contagem','Rua Americo Paulinelli','Rua Américo Paulinelli'),
('BR-MG-Contagem','Rua Americo Santiago Piacenza','Rua Américo Santiago Piacenza'),
('BR-MG-Contagem','Rua Americo de Oliveira','Rua Américo de Oliveira'),
('BR-MG-Contagem','Rua Andromeda','Rua Andrômeda'),
('BR-MG-Contagem','Rua Angela','Rua Ângela'),
('BR-MG-Contagem','Rua Anibal Barca','Rua Aníbal Barca'),
('BR-MG-Contagem','Rua Anita Soares Quintao','Rua Anita Soares Quintão'),
('BR-MG-Contagem','Rua Antonia Alves Vieira Duart','Rua Antônia Alves Vieira Duart'),
('BR-MG-Contagem','Rua Antonia Prates','Rua Antônia Prates'),
('BR-MG-Contagem','Rua Antonio Alves Pimenta','Rua Antônio Alves Pimenta'),
('BR-MG-Contagem','Rua Antonio Alves da Costa','Rua Antônio Alves da Costa'),
('BR-MG-Contagem','Rua Antonio Augusto','Rua Antônio Augusto'),
('BR-MG-Contagem','Rua Antonio Barbosa de Oliveir','Rua Antônio Barbosa de Oliveir'),
('BR-MG-Contagem','Rua Antonio Bernardino Muniz','Rua Antônio Bernardino Muniz'),
('BR-MG-Contagem','Rua Antonio Bernardino de Abre','Rua Antônio Bernardino de Abre'),
('BR-MG-Contagem','Rua Antonio Carlos','Rua Antônio Carlos'),
('BR-MG-Contagem','Rua Antonio Dias','Rua Antônio Dias'),
('BR-MG-Contagem','Rua Antonio Francisco de Camar','Rua Antônio Francisco de Camar'),
('BR-MG-Contagem','Rua Antonio Gaudioso','Rua Antônio Gaudioso'),
('BR-MG-Contagem','Rua Antonio Goncalves Neto','Rua Antônio Gonçalves Neto'),
('BR-MG-Contagem','Rua Antonio Henriques Nogueira','Rua Antônio Henriques Nogueira'),
('BR-MG-Contagem','Rua Antonio Isidoro Moreira','Rua Antônio Isidoro Moreira'),
('BR-MG-Contagem','Rua Antonio Joaquim Santana','Rua Antônio Joaquim Santana'),
('BR-MG-Contagem','Rua Antonio Jose Costinha','Rua Antônio José Costinha'),
('BR-MG-Contagem','Rua Antonio Marcal Muniz','Rua Antônio Marcal Muniz'),
('BR-MG-Contagem','Rua Antonio Maria de Freitas','Rua Antônio Maria de Freitas'),
('BR-MG-Contagem','Rua Antonio Moreira da Silva','Rua Antônio Moreira da Silva'),
('BR-MG-Contagem','Rua Antonio Pinto Lana','Rua Antônio Pinto Lana'),
('BR-MG-Contagem','Rua Antonio Pio da Rocha','Rua Antônio Pio da Rocha'),
('BR-MG-Contagem','Rua Antonio Pires','Rua Antônio Pires'),
('BR-MG-Contagem','Rua Antonio Prado Mello','Rua Antônio Prado Mello'),
('BR-MG-Contagem','Rua Antonio Raposo','Rua Antônio Raposo'),
('BR-MG-Contagem','Rua Antonio Rodrigues Arzao','Rua Antônio Rodrigues Arzão'),
('BR-MG-Contagem','Rua Antonio Teixeira Ferraz','Rua Antônio Teixeira Ferraz'),
('BR-MG-Contagem','Rua Antonio de Oliveira Campos','Rua Antônio de Oliveira Campos'),
('BR-MG-Contagem','Rua Antonio de Padua Pinto','Rua Antônio de Pádua Pinto'),
('BR-MG-Contagem','Rua Aprigio de Andrade','Rua Aprígio de Andrade'),
('BR-MG-Contagem','Rua Aquario','Rua Aquário'),
('BR-MG-Contagem','Rua Araxa','Rua Araxá'),
('BR-MG-Contagem','Rua Augusta Goncalves Nogueira','Rua Augusta Gonçalves Nogueira'),
('BR-MG-Contagem','Rua Augusto Goncalves','Rua Augusto Gonçalves'),
('BR-MG-Contagem','Rua Aurelio Lopes','Rua Aurélio Lopes'),
('BR-MG-Contagem','Rua Azaleia','Rua Azaléia'),
('BR-MG-Contagem','Rua Balnearios','Rua Balneários'),
('BR-MG-Contagem','Rua Barao Cauhiy','Rua Barão Cauhiy'),
('BR-MG-Contagem','Rua Barao de Cotegipe','Rua Barão de Cotegipe'),
('BR-MG-Contagem','Rua Barao do Rio Branco','Rua Barão do Rio Branco'),
('BR-MG-Contagem','Rua Barbara Heliodora','Rua Bárbara Heliodora'),
('BR-MG-Contagem','Rua Begonia','Rua Begônia'),
('BR-MG-Contagem','Rua Belem','Rua Belém'),
('BR-MG-Contagem','Rua Benedito Jose Neves','Rua Benedito José Neves'),
('BR-MG-Contagem','Rua Benfica Magalhaes','Rua Benfica Magalhães'),
('BR-MG-Contagem','Rua Bento Goncalves Filho','Rua Bento Gonçalves Filho'),
('BR-MG-Contagem','Rua Bernardino Candido','Rua Bernardino Cândido'),
('BR-MG-Contagem','Rua Bodas de Canaa','Rua Bodas de Canaã'),
('BR-MG-Contagem','Rua Bolivia','Rua Bolívia'),
('BR-MG-Contagem','Rua Braganca','Rua Bragança'),
('BR-MG-Contagem','Rua Brauna','Rua Braúna'),
('BR-MG-Contagem','Rua Bueno Brandao','Rua Bueno Brandão'),
('BR-MG-Contagem','Rua Buzios','Rua Búzios'),
('BR-MG-Contagem','Rua Cacapava','Rua Caçapava'),
('BR-MG-Contagem','Rua Caiapo','Rua Caiapó'),
('BR-MG-Contagem','Rua Cambara','Rua Cambará'),
('BR-MG-Contagem','Rua Canafistula','Rua Canafístula'),
('BR-MG-Contagem','Rua Caparao','Rua Caparaó'),
('BR-MG-Contagem','Rua Caparao (Antiga Rua M)','Rua Caparaó (Antiga Rua M)'),
('BR-MG-Contagem','Rua Capricornio','Rua Capricórnio'),
('BR-MG-Contagem','Rua Caraiba','Rua Caraíba'),
('BR-MG-Contagem','Rua Carlos Vitoriano de Sa','Rua Carlos Vitoriano de Sá'),
('BR-MG-Contagem','Rua Carmopolis','Rua Carmópolis'),
('BR-MG-Contagem','Rua Carolino Joao Costa','Rua Carolino João Costa'),
('BR-MG-Contagem','Rua Cassia','Rua Cássia'),
('BR-MG-Contagem','Rua Caviuna','Rua Caviúna'),
('BR-MG-Contagem','Rua Celeste Imperio','Rua Celeste Ímpério'),
('BR-MG-Contagem','Rua Cinquenta e Tres','Rua Cinquenta e Três'),
('BR-MG-Contagem','Rua Claudio','Rua Cláudio'),
('BR-MG-Contagem','Rua Claudio Manoel','Rua Cláudio Manoel'),
('BR-MG-Contagem','Rua Clemente Anibal Branco','Rua Clemente Aníbal Branco'),
('BR-MG-Contagem','Rua Clovis Antonio de Freitas','Rua Clóvis Antônio de Freitas'),
('BR-MG-Contagem','Rua Colombia','Rua Colômbia'),
('BR-MG-Contagem','Rua Conceicao Maria Diniz','Rua Conceição Maria Diniz'),
('BR-MG-Contagem','Rua Confrade Luis Orsini','Rua Confrade Luís Orsini'),
('BR-MG-Contagem','Rua Cornelio Belem','Rua Cornélio Belém'),
('BR-MG-Contagem','Rua Cornelio Vaz Melo','Rua Cornélio Vaz Melo'),
('BR-MG-Contagem','Rua Coronel Americo Leite','Rua Coronel Américo Leite'),
('BR-MG-Contagem','Rua Coronel Antonio B. Camargos','Rua Coronel Antônio B. Camargos'),
('BR-MG-Contagem','Rua Coronel Antonio Luciano Perei','Rua Coronel Antônio Luciano Perei'),
('BR-MG-Contagem','Rua Coronel Antonio de Cassia','Rua Coronel Antônio de Cássia'),
('BR-MG-Contagem','Rua Coronel Atila Vilela','Rua Coronel Átila Vilela'),
('BR-MG-Contagem','Rua Coronel Gabriel Romao Carneiro','Rua Coronel Gabriel Romão Carneiro'),
('BR-MG-Contagem','Rua Coronel Joao Camargos','Rua Coronel João Camargos'),
('BR-MG-Contagem','Rua Coronel Joao Modesto','Rua Coronel João Modesto'),
('BR-MG-Contagem','Rua Coronel Joao Renno','Rua Coronel João Renno'),
('BR-MG-Contagem','Rua Coronel Jose Domingos Baeta','Rua Coronel José Domingos Baeta'),
('BR-MG-Contagem','Rua Coronel Jose Pedro de Araujo','Rua Coronel José Pedro de Araújo'),
('BR-MG-Contagem','Rua Coronel Licinio Dutra','Rua Coronel Licínio Dutra'),
('BR-MG-Contagem','Rua Coronel Mario Campos','Rua Coronel Mário Campos'),
('BR-MG-Contagem','Rua Corumba','Rua Corumbá'),
('BR-MG-Contagem','Rua Cristovao Macedo','Rua Cristóvão Macedo'),
('BR-MG-Contagem','Rua Cubatao','Rua Cubatão'),
('BR-MG-Contagem','Rua Custodio Maia','Rua Custódio Maia'),
('BR-MG-Contagem','Rua Dalia','Rua Dália'),
('BR-MG-Contagem','Rua Decio Camargos de Aguiar','Rua Décio Camargos de Aguiar'),
('BR-MG-Contagem','Rua Delio da Consolacao Rocha','Rua Délio da Consolação Rocha'),
('BR-MG-Contagem','Rua Deputado Sergio Miranda','Rua Deputado Sérgio Miranda'),
('BR-MG-Contagem','Rua Diogenes Nogueira','Rua Diógenes Nogueira'),
('BR-MG-Contagem','Rua Dom Joao dos Santos','Rua Dom João dos Santos'),
('BR-MG-Contagem','Rua Dom Silverio','Rua Dom Silvério'),
('BR-MG-Contagem','Rua Domingos Belem','Rua Domingos Belém'),
('BR-MG-Contagem','Rua Domingos Jose','Rua Domingos José'),
('BR-MG-Contagem','Rua Domingos Jose Belem','Rua Domingos José Belém'),
('BR-MG-Contagem','Rua Domingos do Sitio','Rua Domingos do Sítio'),
('BR-MG-Contagem','Rua Dona Ana Candida','Rua Dona Ana Cândida'),
('BR-MG-Contagem','Rua Dona Augusta Goncalves Nog','Rua Dona Augusta Gonçalves Nog'),
('BR-MG-Contagem','Rua Dona Ines Carlota','Rua Dona Inês Carlota'),
('BR-MG-Contagem','Rua Dorcelina Candida da Silva','Rua Dorcelina Cândida da Silva'),
('BR-MG-Contagem','Rua Doutor Antonio Xavier Almeida','Rua Doutor Antônio Xavier Almeida'),
('BR-MG-Contagem','Rua Ebano','Rua Ébano'),
('BR-MG-Contagem','Rua Edmir Leao','Rua Edmir Leão'),
('BR-MG-Contagem','Rua Efigenia Matos Paixao','Rua Efigênia Matos Paixão'),
('BR-MG-Contagem','Rua Elias Perpetuo Oliveira','Rua Elias Perpétuo Oliveira'),
('BR-MG-Contagem','Rua Emaus','Rua Emaús'),
('BR-MG-Contagem','Rua Emilia Silva de Freitas','Rua Emília Silva de Freitas'),
('BR-MG-Contagem','Rua Emilio Maciel','Rua Emílio Maciel'),
('BR-MG-Contagem','Rua Engenheiro Sodre','Rua Engenheiro Sodré'),
('BR-MG-Contagem','Rua Epitacio Pessoa','Rua Epitácio Pessoa'),
('BR-MG-Contagem','Rua Espirito Santo','Rua Espírito Santo'),
('BR-MG-Contagem','Rua Eufrasia Augusta de Jesus','Rua Eufrásia Augusta de Jesus'),
('BR-MG-Contagem','Rua Eugenia Sa Fortes','Rua Eugênia Sá Fortes'),
('BR-MG-Contagem','Rua Eugenio Cardoso da Silva','Rua Eugênio Cardoso da Silva'),
('BR-MG-Contagem','Rua Eugenio Napoli','Rua Eugênio Napoli'),
('BR-MG-Contagem','Rua Eugenopolis','Rua Eugenópolis'),
('BR-MG-Contagem','Rua Expedicionário Walter Magalhaes','Rua Expedicionário Walter Magalhães'),
('BR-MG-Contagem','Rua Fabio Rosario Diniz','Rua Fábio Rosário Diniz'),
('BR-MG-Contagem','Rua Farmaceutico Lirio de Cast','Rua Farmacêutico Lírio de Cast'),
('BR-MG-Contagem','Rua Fatima','Rua Fátima'),
('BR-MG-Contagem','Rua Felix Francisco Chamon','Rua Félíx Francisco Chamon'),
('BR-MG-Contagem','Rua Felix de Almeida','Rua Félíx de Almeida'),
('BR-MG-Contagem','Rua Fenix','Rua Fênix'),
('BR-MG-Contagem','Rua Fiscal Joao Militao','Rua Fiscal João Militão'),
('BR-MG-Contagem','Rua Flavio Annes Guimaraes','Rua Flávio Annes Guimarães'),
('BR-MG-Contagem','Rua Flor de Ipe','Rua Flor de Ipê'),
('BR-MG-Contagem','Rua Florenca','Rua Florença'),
('BR-MG-Contagem','Rua Francisco Goncalves','Rua Francisco Gonçalves'),
('BR-MG-Contagem','Rua Francisco de Avila','Rua Francisco de Ávila'),
('BR-MG-Contagem','Rua Garcas','Rua Garças'),
('BR-MG-Contagem','Rua Gardenia','Rua Gardênia'),
('BR-MG-Contagem','Rua Geraldo Antonio Oliveira','Rua Geraldo Antônio Oliveira'),
('BR-MG-Contagem','Rua Geraldo Januario de Araujo','Rua Geraldo Januário de Araújo'),
('BR-MG-Contagem','Rua Geraldo Joao de Deus','Rua Geraldo João de Deus'),
('BR-MG-Contagem','Rua Geraldo Magela Belem','Rua Geraldo Magela Belém'),
('BR-MG-Contagem','Rua Gervasio Silva','Rua Gervásio Silva'),
('BR-MG-Contagem','Rua Getulio Vargas','Rua Getúlio Vargas'),
('BR-MG-Contagem','Rua Giovani Jose Chiodi','Rua Giovani José Chiodi'),
('BR-MG-Contagem','Rua Goias','Rua Goiás'),
('BR-MG-Contagem','Rua Goncalo Ferreira','Rua Gonçalo Ferreira'),
('BR-MG-Contagem','Rua Goncalves Dias','Rua Gonçalves Dias'),
('BR-MG-Contagem','Rua Gualter Rocha','Rua Guálter Rocha'),
('BR-MG-Contagem','Rua Guanhaes','Rua Guanhães'),
('BR-MG-Contagem','Rua Guape','Rua Guapé'),
('BR-MG-Contagem','Rua Guara','Rua Guará'),
('BR-MG-Contagem','Rua Guaxupe','Rua Guaxupé'),
('BR-MG-Contagem','Rua Guimaraes Rosa','Rua Guimarães Rosa'),
('BR-MG-Contagem','Rua Helia Ricaldoni Freitas','Rua Hélia Ricaldoni Freitas'),
('BR-MG-Contagem','Rua Helio Martins dos Reis','Rua Hélio Martins dos Reis'),
('BR-MG-Contagem','Rua Honorita Siria dos Santos','Rua Honorita Síria dos Santos'),
('BR-MG-Contagem','Rua Humaita','Rua Humaitá'),
('BR-MG-Contagem','Rua Igarape','Rua Igarapé'),
('BR-MG-Contagem','Rua Igor','Rua Ígor'),
('BR-MG-Contagem','Rua Iguacaba','Rua Iguaçaba'),
('BR-MG-Contagem','Rua Ilheus','Rua Ilhéus'),
('BR-MG-Contagem','Rua Imola','Rua Ímola'),
('BR-MG-Contagem','Rua Inga','Rua Ingá'),
('BR-MG-Contagem','Rua Ipe','Rua Ipê'),
('BR-MG-Contagem','Rua Irece','Rua Irecê'),
('BR-MG-Contagem','Rua Isaias Jose Diniz','Rua Isaías José Diniz'),
('BR-MG-Contagem','Rua Italia','Rua Itália'),
('BR-MG-Contagem','Rua Itambe','Rua Itambé'),
('BR-MG-Contagem','Rua Itapoa','Rua Itapoã'),
('BR-MG-Contagem','Rua Jacaranda','Rua Jacarandá'),
('BR-MG-Contagem','Rua Jacareipe','Rua Jacareípe'),
('BR-MG-Contagem','Rua Jaguarao','Rua Jaguarão'),
('BR-MG-Contagem','Rua Janauba','Rua Janaúba'),
('BR-MG-Contagem','Rua Januaria','Rua Januária'),
('BR-MG-Contagem','Rua Jaragua','Rua Jaraguá'),
('BR-MG-Contagem','Rua Jardim America','Rua Jardim América'),
('BR-MG-Contagem','Rua Jatoba','Rua Jatobá'),
('BR-MG-Contagem','Rua Jequitiba','Rua Jequitibá'),
('BR-MG-Contagem','Rua Jequitibas','Rua Jequitibás'),
('BR-MG-Contagem','Rua Jeronimo Soares Barbosa','Rua Jerônimo Soares Barbosa'),
('BR-MG-Contagem','Rua Joao Antonio Faria','Rua João Antônio Faria'),
('BR-MG-Contagem','Rua Joao Batista Costa Pio','Rua João Batista Costa Pio'),
('BR-MG-Contagem','Rua Joao Bosco Martins','Rua João Bosco Martins'),
('BR-MG-Contagem','Rua Joao Brigido Ribeiro','Rua João Brígido Ribeiro'),
('BR-MG-Contagem','Rua Joao Cisenando Costa','Rua João Cisenando Costa'),
('BR-MG-Contagem','Rua Joao Damasceno','Rua João Damasceno'),
('BR-MG-Contagem','Rua Joao Ferreira','Rua João Ferreira'),
('BR-MG-Contagem','Rua Joao Ferreira Aguiar','Rua João Ferreira Aguiar'),
('BR-MG-Contagem','Rua Joao Ferreira Gomes','Rua João Ferreira Gomes'),
('BR-MG-Contagem','Rua Joao Franco','Rua João Franco'),
('BR-MG-Contagem','Rua Joao Gomes','Rua João Gomes'),
('BR-MG-Contagem','Rua Joao Gomes Cardoso','Rua João Gomes Cardoso'),
('BR-MG-Contagem','Rua Joao Gualberto Costa','Rua João Gualberto Costa'),
('BR-MG-Contagem','Rua Joao Gualberto Jesus','Rua João Gualberto Jesus'),
('BR-MG-Contagem','Rua Joao Guimaraes','Rua João Guimarães'),
('BR-MG-Contagem','Rua Joao Jose Almeida','Rua João José Almeida'),
('BR-MG-Contagem','Rua Joao Lima','Rua João Lima'),
('BR-MG-Contagem','Rua Joao M. Jose','Rua João M. José'),
('BR-MG-Contagem','Rua Joao Nogueira','Rua João Nogueira'),
('BR-MG-Contagem','Rua Joao Pacheco da Cruz','Rua João Pacheco da Cruz'),
('BR-MG-Contagem','Rua Joao Paulo','Rua João Paulo'),
('BR-MG-Contagem','Rua Joao Paulo Amorim','Rua João Paulo Amorim'),
('BR-MG-Contagem','Rua Joao Penedo Alves','Rua João Penedo Alves'),
('BR-MG-Contagem','Rua Joao Pio da Rocha','Rua João Pio da Rocha'),
('BR-MG-Contagem','Rua Joao Ribeiro','Rua João Ribeiro'),
('BR-MG-Contagem','Rua Joao Rosa','Rua João Rosa'),
('BR-MG-Contagem','Rua Joao Silva Diniz','Rua João Silva Diniz'),
('BR-MG-Contagem','Rua Joao Venancio Ferreira','Rua João Venâncio Ferreira'),
('BR-MG-Contagem','Rua Joao Wanderey','Rua João Wanderey'),
('BR-MG-Contagem','Rua Joao da Mata','Rua João da Mata'),
('BR-MG-Contagem','Rua Joao de Souza Souto','Rua João de Souza Souto'),
('BR-MG-Contagem','Rua Joaquim Jose','Rua Joaquim José'),
('BR-MG-Contagem','Rua Joaquim Jose Diniz','Rua Joaquim José Diniz'),
('BR-MG-Contagem','Rua Joaquim Jose Diniz-Quincas','Rua Joaquim José Diniz-Quincas'),
('BR-MG-Contagem','Rua Jose Afonso Barbosa Melo','Rua José Afonso Barbosa Melo'),
('BR-MG-Contagem','Rua Jose Aleixo de Souza','Rua José Aleixo de Souza'),
('BR-MG-Contagem','Rua Jose Amado Silva','Rua José Amado Silva'),
('BR-MG-Contagem','Rua Jose Andre Luiz','Rua José André Luiz'),
('BR-MG-Contagem','Rua Jose Antonio Ribeiro','Rua José Antônio Ribeiro'),
('BR-MG-Contagem','Rua Jose Antonio Tomaz Filho','Rua José Antônio Tomaz Filho'),
('BR-MG-Contagem','Rua Jose Antunes','Rua José Antunes'),
('BR-MG-Contagem','Rua Jose Armando da Rocha','Rua José Armando da Rocha'),
('BR-MG-Contagem','Rua Jose Augusto Mendonca','Rua José Augusto Mendonça'),
('BR-MG-Contagem','Rua Jose Augusto Rocha','Rua José Augusto Rocha'),
('BR-MG-Contagem','Rua Jose Barra do Nascimento','Rua José Barra do Nascimento'),
('BR-MG-Contagem','Rua Jose Basilio','Rua José Basílio'),
('BR-MG-Contagem','Rua Jose Bicalho','Rua José Bicalho'),
('BR-MG-Contagem','Rua Jose Brandao','Rua José Brandão'),
('BR-MG-Contagem','Rua Jose Cairo Militao','Rua José Cairo Militão'),
('BR-MG-Contagem','Rua Jose Candido Palhares','Rua José Cândido Palhares'),
('BR-MG-Contagem','Rua Jose Carlos Camargos','Rua José Carlos Camargos'),
('BR-MG-Contagem','Rua Jose Cavaline','Rua José Cavaline'),
('BR-MG-Contagem','Rua Jose Celestino','Rua José Celestino'),
('BR-MG-Contagem','Rua Jose Costa Ferreira','Rua José Costa Ferreira'),
('BR-MG-Contagem','Rua Jose Custodio','Rua José Custódio'),
('BR-MG-Contagem','Rua Jose Diniz Maia','Rua José Diniz Maia'),
('BR-MG-Contagem','Rua Jose Feliciano de Azevedo','Rua José Feliciano de Azevedo'),
('BR-MG-Contagem','Rua Jose Fernandes Santos','Rua José Fernandes Santos'),
('BR-MG-Contagem','Rua Jose Fernando Gomes de Oli','Rua José Fernando Gomes de Oli'),
('BR-MG-Contagem','Rua Jose Ferreira Soares','Rua José Ferreira Soares'),
('BR-MG-Contagem','Rua Jose Francisco Assis','Rua José Francisco Assis'),
('BR-MG-Contagem','Rua Jose Francisco da Cruz','Rua José Francisco da Cruz'),
('BR-MG-Contagem','Rua Jose Geraldo da Silva','Rua José Geraldo da Silva'),
('BR-MG-Contagem','Rua Jose Gomes Pinheiro','Rua José Gomes Pinheiro'),
('BR-MG-Contagem','Rua Jose Goncalves','Rua José Gonçalves'),
('BR-MG-Contagem','Rua Jose Goncalves Filho','Rua José Gonçalves Filho'),
('BR-MG-Contagem','Rua Jose Horta Costa','Rua José Horta Costa'),
('BR-MG-Contagem','Rua Jose Izidoro','Rua José Izidoro'),
('BR-MG-Contagem','Rua Jose Leite de Carvalho','Rua José Leite de Carvalho'),
('BR-MG-Contagem','Rua Jose Lopes Goncalves','Rua José Lopes Gonçalves'),
('BR-MG-Contagem','Rua Jose Lucas de Oliveira','Rua José Lucas de Oliveira'),
('BR-MG-Contagem','Rua Jose Maria Santana','Rua José Maria Santana'),
('BR-MG-Contagem','Rua Jose Maria de Lacerda','Rua José Maria de Lacerda'),
('BR-MG-Contagem','Rua Jose Martins Borges','Rua José Martins Borges'),
('BR-MG-Contagem','Rua Jose Medeiros Leite','Rua José Medeiros Leite'),
('BR-MG-Contagem','Rua Jose Mendes Ferreira','Rua José Mendes Ferreira'),
('BR-MG-Contagem','Rua Jose Narciso Campos','Rua José Narciso Campos'),
('BR-MG-Contagem','Rua Jose Patrocinio','Rua José Patrocínio'),
('BR-MG-Contagem','Rua Jose Paulino de Oliveira L','Rua José Paulino de Oliveira L'),
('BR-MG-Contagem','Rua Jose Pedro Araujo','Rua José Pedro Araújo'),
('BR-MG-Contagem','Rua Jose Penido','Rua José Penido'),
('BR-MG-Contagem','Rua Jose Pereira Franco','Rua José Pereira Franco'),
('BR-MG-Contagem','Rua Jose Perminio da Silva','Rua José Perminio da Silva'),
('BR-MG-Contagem','Rua Jose Pio da Rocha','Rua José Pio da Rocha'),
('BR-MG-Contagem','Rua Jose Rodrigues Guilherme','Rua José Rodrigues Guilherme'),
('BR-MG-Contagem','Rua Jose Souza Arruda','Rua José Souza Arruda'),
('BR-MG-Contagem','Rua Jose Tavares dos Santos','Rua José Tavares dos Santos'),
('BR-MG-Contagem','Rua Jose Vasconcelos Monteiro','Rua José Vasconcelos Monteiro'),
('BR-MG-Contagem','Rua Jose da Silva Couto','Rua José da Silva Couto'),
('BR-MG-Contagem','Rua Jose de Paula Filho','Rua José de Paula Filho'),
('BR-MG-Contagem','Rua Jose de Souza','Rua José de Souza'),
('BR-MG-Contagem','Rua Jose de Souza Arruda','Rua José de Souza Arruda'),
('BR-MG-Contagem','Rua Jose do Patrocinio','Rua José do Patrocínio'),
('BR-MG-Contagem','Rua Jove Simao','Rua Jove Simão'),
('BR-MG-Contagem','Rua Juca Flavio','Rua Juca Flávio'),
('BR-MG-Contagem','Rua Jupiter','Rua Júpiter'),
('BR-MG-Contagem','Rua Lapis Lazuli','Rua Lápis Lazuli'),
('BR-MG-Contagem','Rua Latania','Rua Latânia'),
('BR-MG-Contagem','Rua Lucia Canedo','Rua Lúcia Canedo'),
('BR-MG-Contagem','Rua Lucia Maria Pereira Diniz','Rua Lúcia Maria Pereira Diniz'),
('BR-MG-Contagem','Rua Luiz Guimaraes','Rua Luiz Guimarães'),
('BR-MG-Contagem','Rua Macae','Rua Macaé'),
('BR-MG-Contagem','Rua Macapa','Rua Macapá'),
('BR-MG-Contagem','Rua Macaubas','Rua Macaúbas'),
('BR-MG-Contagem','Rua Magnolia','Rua Magnólia'),
('BR-MG-Contagem','Rua Major Joao Alexandre','Rua Major João Alexandre'),
('BR-MG-Contagem','Rua Mamore','Rua Mamoré'),
('BR-MG-Contagem','Rua Manaca','Rua Manacá'),
('BR-MG-Contagem','Rua Manoel Alves Basilio','Rua Manoel Alves Basílio'),
('BR-MG-Contagem','Rua Manoel Antonio Xavier','Rua Manoel Antônio Xavier'),
('BR-MG-Contagem','Rua Manoel Brandao','Rua Manoel Brandão'),
('BR-MG-Contagem','Rua Manoel Goncalves','Rua Manoel Gonçalves'),
('BR-MG-Contagem','Rua Manoel Goncalves Rezende','Rua Manoel Gonçalves Rezende'),
('BR-MG-Contagem','Rua Manoel Joao Diniz Camargos','Rua Manoel João Diniz Camargos'),
('BR-MG-Contagem','Rua Manoel Jose Dutra','Rua Manoel José Dutra'),
('BR-MG-Contagem','Rua Manoel da Nobrega','Rua Manoel da Nóbrega'),
('BR-MG-Contagem','Rua Maraba','Rua Marabá'),
('BR-MG-Contagem','Rua Marajo','Rua Marajó'),
('BR-MG-Contagem','Rua Maranhao','Rua Maranhão'),
('BR-MG-Contagem','Rua Marataizes','Rua Marataízes'),
('BR-MG-Contagem','Rua Maria Augusta Belem','Rua Maria Augusta Belém'),
('BR-MG-Contagem','Rua Maria Candida','Rua Maria Cândida'),
('BR-MG-Contagem','Rua Maria Cecilia','Rua Maria Cecília'),
('BR-MG-Contagem','Rua Maria Ines','Rua Maria Inês'),
('BR-MG-Contagem','Rua Maria Izabel da Conceicao','Rua Maria Izabel da Conceição'),
('BR-MG-Contagem','Rua Maria Jose da Rocha','Rua Maria José da Rocha'),
('BR-MG-Contagem','Rua Maria Julia Diniz','Rua Maria Júlia Diniz'),
('BR-MG-Contagem','Rua Maria da Conceicao Hilario','Rua Maria da Conceição Hilário'),
('BR-MG-Contagem','Rua Maria de Sao Jose','Rua Maria de São José'),
('BR-MG-Contagem','Rua Mario Pinheiro de Souza','Rua Mário Pinheiro de Souza'),
('BR-MG-Contagem','Rua Mario Vital','Rua Mário Vital'),
('BR-MG-Contagem','Rua Matipo','Rua Matipó'),
('BR-MG-Contagem','Rua Mercurio','Rua Mercúrio'),
('BR-MG-Contagem','Rua Monaco','Rua Mônaco'),
('BR-MG-Contagem','Rua Monsenhor Joao Martins','Rua Monsenhor João Martins'),
('BR-MG-Contagem','Rua Monsenhor Joao Rodrigues','Rua Monsenhor João Rodrigues'),
('BR-MG-Contagem','Rua Monsenhor Leao','Rua Monsenhor Leão'),
('BR-MG-Contagem','Rua Montevideu','Rua Montevidéu'),
('BR-MG-Contagem','Rua Necesio Tavares','Rua Necésio Tavares'),
('BR-MG-Contagem','Rua Nicaragua','Rua Nicarágua'),
('BR-MG-Contagem','Rua Nilo Pecanha','Rua Nilo Peçanha'),
('BR-MG-Contagem','Rua Nossa Senhora Perpetuo Soc','Rua Nossa Senhora Perpétuo Soc'),
('BR-MG-Contagem','Rua Nossa Senhora da Conceicao','Rua Nossa Senhora da Conceição'),
('BR-MG-Contagem','Rua Nossa Senhora das Gracas','Rua Nossa Senhora das Graças'),
('BR-MG-Contagem','Rua Nova Brasilia','Rua Nova Brasília'),
('BR-MG-Contagem','Rua Oitenta e Tres','Rua Oitenta e Três'),
('BR-MG-Contagem','Rua Oito (Coronel Procopio)','Rua Oito (Coronel Procópio)'),
('BR-MG-Contagem','Rua Olimpio Francisco da Silva','Rua Olímpio Francisco da Silva'),
('BR-MG-Contagem','Rua Onix','Rua Ônix'),
('BR-MG-Contagem','Rua Orquidea','Rua Orquídea'),
('BR-MG-Contagem','Rua Osorio de Moraes','Rua Osório de Moraes'),
('BR-MG-Contagem','Rua Osorio de Morais','Rua Osório de Morais'),
('BR-MG-Contagem','Rua Ovidio de Abreu','Rua Ovídio de Abreu'),
('BR-MG-Contagem','Rua Padre Antonio Vieira','Rua Padre Antônio Vieira'),
('BR-MG-Contagem','Rua Padre Bartolomeu Gusmao','Rua Padre Bartolomeu Gusmão'),
('BR-MG-Contagem','Rua Padre Eustaquio','Rua Padre Eustáquio'),
('BR-MG-Contagem','Rua Padre Feijo','Rua Padre Feijó'),
('BR-MG-Contagem','Rua Padre Flavio','Rua Padre Flávio'),
('BR-MG-Contagem','Rua Padre Goncalves','Rua Padre Gonçalves'),
('BR-MG-Contagem','Rua Padre Goncalves Lopes','Rua Padre Gonçalves Lopes'),
('BR-MG-Contagem','Rua Padre Joao','Rua Padre João'),
('BR-MG-Contagem','Rua Padre Joao de Deus','Rua Padre João de Deus'),
('BR-MG-Contagem','Rua Padre Jose Alves','Rua Padre José Alves'),
('BR-MG-Contagem','Rua Padre Jose Carvalho','Rua Padre José Carvalho'),
('BR-MG-Contagem','Rua Padre Jose Maria de Man','Rua Padre José Maria de Man'),
('BR-MG-Contagem','Rua Padre Julio Maria','Rua Padre Júlio Maria'),
('BR-MG-Contagem','Rua Padre Olimpio','Rua Padre Olímpio'),
('BR-MG-Contagem','Rua Panama','Rua Panamá'),
('BR-MG-Contagem','Rua Paraiba','Rua Paraíba'),
('BR-MG-Contagem','Rua Paraiso','Rua Paraíso'),
('BR-MG-Contagem','Rua Parana','Rua Paraná'),
('BR-MG-Contagem','Rua Passaro Preto','Rua Pássaro Preto'),
('BR-MG-Contagem','Rua Paulo Bufalo','Rua Paulo Búfalo'),
('BR-MG-Contagem','Rua Paulo Sergio','Rua Paulo Sérgio'),
('BR-MG-Contagem','Rua Paulo de Barros Baia','Rua Paulo de Barros Baía'),
('BR-MG-Contagem','Rua Pedro Alcantara','Rua Pedro Alcântara'),
('BR-MG-Contagem','Rua Pedro Belem','Rua Pedro Belém'),
('BR-MG-Contagem','Rua Pedro Cesar','Rua Pedro César'),
('BR-MG-Contagem','Rua Penetracao Quatro','Rua Penetração Quatro'),
('BR-MG-Contagem','Rua Pericles Gomide','Rua Péricles Gomide'),
('BR-MG-Contagem','Rua Petropolis','Rua Petrópolis'),
('BR-MG-Contagem','Rua Petroquimica','Rua Petroquímica'),
('BR-MG-Contagem','Rua Petunia','Rua Petúnia'),
('BR-MG-Contagem','Rua Pitagoras','Rua Pitágoras'),
('BR-MG-Contagem','Rua Pocos de Caldas','Rua Poços de Caldas'),
('BR-MG-Contagem','Rua Pompeia','Rua Pompéia'),
('BR-MG-Contagem','Rua Porcina Gomes Araujo','Rua Porcina Gomes Araújo'),
('BR-MG-Contagem','Rua Presbitero Joao Rosa da Si','Rua Presbítero João Rosa da Si'),
('BR-MG-Contagem','Rua Presbitero Santino de Souz','Rua Presbítero Santino de Souz'),
('BR-MG-Contagem','Rua Primo Horario','Rua Primo Horário'),
('BR-MG-Contagem','Rua Professor Jose Americano','Rua Professor José Americano'),
('BR-MG-Contagem','Rua Quarenta e Tres','Rua Quarenta e Três'),
('BR-MG-Contagem','Rua Reconcavo','Rua Recôncavo'),
('BR-MG-Contagem','Rua Refinaria Cubatao','Rua Refinaria Cubatão'),
('BR-MG-Contagem','Rua Refinaria Uniao','Rua Refinaria União'),
('BR-MG-Contagem','Rua Regino Inocencio de Souza','Rua Regino Inocêncio de Souza'),
('BR-MG-Contagem','Rua Republica','Rua República'),
('BR-MG-Contagem','Rua Rio Abaete','Rua Rio Abaeté'),
('BR-MG-Contagem','Rua Rio Aimores','Rua Rio Aimorés'),
('BR-MG-Contagem','Rua Rio Cuiaba','Rua Rio Cuiabá'),
('BR-MG-Contagem','Rua Rio Danubio','Rua Rio Danúbio'),
('BR-MG-Contagem','Rua Rio Indaia','Rua Rio Indaiá'),
('BR-MG-Contagem','Rua Rio Jordao','Rua Rio Jordão'),
('BR-MG-Contagem','Rua Rio Mamore','Rua Rio Mamoré'),
('BR-MG-Contagem','Rua Rio Maranhao','Rua Rio Maranhão'),
('BR-MG-Contagem','Rua Rio Mossoro','Rua Rio Mossoró'),
('BR-MG-Contagem','Rua Rio Paraiba','Rua Rio Paraíba'),
('BR-MG-Contagem','Rua Rio Parana','Rua Rio Paraná'),
('BR-MG-Contagem','Rua Rio Paranagua','Rua Rio Paranaguá'),
('BR-MG-Contagem','Rua Rio Parnaiba','Rua Rio Parnaíba'),
('BR-MG-Contagem','Rua Rio Sao Joao','Rua Rio São João'),
('BR-MG-Contagem','Rua Rio Sao Lourenco','Rua Rio São Lourenço'),
('BR-MG-Contagem','Rua Rio Solimoes','Rua Rio Solimões'),
('BR-MG-Contagem','Rua Rio Tapajos','Rua Rio Tapajós'),
('BR-MG-Contagem','Rua Rio Tiete','Rua Rio Tietê'),
('BR-MG-Contagem','Rua Roldao Miranda','Rua Roldão Miranda'),
('BR-MG-Contagem','Rua Rouxinois','Rua Rouxinóis'),
('BR-MG-Contagem','Rua Ruth Custodio','Rua Ruth Custódio'),
('BR-MG-Contagem','Rua Sabara','Rua Sabará'),
('BR-MG-Contagem','Rua Sabias','Rua Sabiás'),
('BR-MG-Contagem','Rua Sagitario','Rua Sagitário'),
('BR-MG-Contagem','Rua Sagrada Familia','Rua Sagrada Família'),
('BR-MG-Contagem','Rua Sagrado Coracao de Jesus','Rua Sagrado Coração de Jesus'),
('BR-MG-Contagem','Rua Santa Barbara','Rua Santa Bárbara'),
('BR-MG-Contagem','Rua Santa Ines','Rua Santa Inês'),
('BR-MG-Contagem','Rua Santarem','Rua Santarém'),
('BR-MG-Contagem','Rua Santo Antonio','Rua Santo Antônio'),
('BR-MG-Contagem','Rua Sao Borja','Rua São Borja'),
('BR-MG-Contagem','Rua Sao Conrado','Rua São Conrado'),
('BR-MG-Contagem','Rua Sao Dimas','Rua São Dimas'),
('BR-MG-Contagem','Rua Sao Domingos','Rua São Domingos'),
('BR-MG-Contagem','Rua Sao Francisco','Rua São Francisco'),
('BR-MG-Contagem','Rua Sao Geraldo','Rua São Geraldo'),
('BR-MG-Contagem','Rua Sao Goncalo','Rua São Gonçalo'),
('BR-MG-Contagem','Rua Sao Gotardo','Rua São Gotardo'),
('BR-MG-Contagem','Rua Sao Joao','Rua São João'),
('BR-MG-Contagem','Rua Sao Jose','Rua São José'),
('BR-MG-Contagem','Rua Sao Leopoldo','Rua São Leopoldo'),
('BR-MG-Contagem','Rua Sao Lourenco','Rua São Lourenço'),
('BR-MG-Contagem','Rua Sao Lucas','Rua São Lucas'),
('BR-MG-Contagem','Rua Sao Luiz','Rua São Luiz'),
('BR-MG-Contagem','Rua Sao Marcos','Rua São Marcos'),
('BR-MG-Contagem','Rua Sao Mateus','Rua São Mateus'),
('BR-MG-Contagem','Rua Sao Miguel','Rua São Miguel'),
('BR-MG-Contagem','Rua Sao Salvador','Rua São Salvador'),
('BR-MG-Contagem','Rua Sao Sebastiao','Rua São Sebastião'),
('BR-MG-Contagem','Rua Sao Tomaz de Aquino','Rua São Tomaz de Aquino'),
('BR-MG-Contagem','Rua Sao Vicente','Rua São Vicente'),
('BR-MG-Contagem','Rua Sargento Antonio Lourenco','Rua Sargento Antônio Lourenço'),
('BR-MG-Contagem','Rua Satelite','Rua Satélite'),
('BR-MG-Contagem','Rua Sebastiao Gregorio Machado','Rua Sebastião Gregório Machado'),
('BR-MG-Contagem','Rua Sebastiao Izidoro Herculan','Rua Sebastião Izidoro Herculan'),
('BR-MG-Contagem','Rua Sebastiao Limoni','Rua Sebastião Limoni'),
('BR-MG-Contagem','Rua Sebastiao Viana','Rua Sebastião Viana'),
('BR-MG-Contagem','Rua Sebastiao da Cruz Gonzaga','Rua Sebastião da Cruz Gonzaga'),
('BR-MG-Contagem','Rua Semeao','Rua Semeão'),
('BR-MG-Contagem','Rua Senador Lucio Bitencourt','Rua Senador Lúcio Bitencourt'),
('BR-MG-Contagem','Rua Senhora das Gracas','Rua Senhora das Graças'),
('BR-MG-Contagem','Rua Senhora de Fatima','Rua Senhora de Fátima'),
('BR-MG-Contagem','Rua Sequoia','Rua Sequóia'),
('BR-MG-Contagem','Rua Servidao Cia Itau','Rua Servidão Cia Itau'),
('BR-MG-Contagem','Rua Sessenta e Tres','Rua Sessenta e Três'),
('BR-MG-Contagem','Rua Setenta e Tres','Rua Setenta e Três'),
('BR-MG-Contagem','Rua Severo Belem','Rua Severo Belém'),
('BR-MG-Contagem','Rua Silvio Barbosa','Rua Sílvio Barbosa'),
('BR-MG-Contagem','Rua Silvio Neves Martins','Rua Sílvio Neves Martins'),
('BR-MG-Contagem','Rua Simao Antonio','Rua Simão Antônio'),
('BR-MG-Contagem','Rua Simonesia','Rua Simonésia'),
('BR-MG-Contagem','Rua Sindicalista Lucio Guterre','Rua Sindicalista Lúcio Guterre'),
('BR-MG-Contagem','Rua Sinfronio de Souza e Silva','Rua Sinfrônio de Souza e Silva'),
('BR-MG-Contagem','Rua Suica','Rua Suíça'),
('BR-MG-Contagem','Rua Tapajos','Rua Tapajós'),
('BR-MG-Contagem','Rua Tapirai','Rua Tapiraí'),
('BR-MG-Contagem','Rua Tefe','Rua Tefé'),
('BR-MG-Contagem','Rua Teleferico do Itau','Rua Teleférico do Itau'),
('BR-MG-Contagem','Rua Teofilo Otoni','Rua Teófilo Otoni'),
('BR-MG-Contagem','Rua Tereza Goncalves','Rua Tereza Gonçalves'),
('BR-MG-Contagem','Rua Tiburcio Custodio','Rua Tibúrcio Custódio'),
('BR-MG-Contagem','Rua Tiete','Rua Tietê'),
('BR-MG-Contagem','Rua Topazio','Rua Topázio'),
('BR-MG-Contagem','Rua Trajano Araujo Viana','Rua Trajano Araújo Viana'),
('BR-MG-Contagem','Rua Tres','Rua Três'),
('BR-MG-Contagem','Rua Tres (Conjunto Columbia)','Rua Três (Conjunto Colúmbia)'),
('BR-MG-Contagem','Rua Trinta e Tres','Rua Trinta e Três'),
('BR-MG-Contagem','Rua Tronco do Ipe','Rua Tronco do Ipê'),
('BR-MG-Contagem','Rua Tupa','Rua Tupã'),
('BR-MG-Contagem','Rua Unai','Rua Unaí'),
('BR-MG-Contagem','Rua Uniao de Contagem','Rua União de Contagem'),
('BR-MG-Contagem','Rua Urupes','Rua Urupês'),
('BR-MG-Contagem','Rua Valenca','Rua Valença'),
('BR-MG-Contagem','Rua Venus','Rua Vênus'),
('BR-MG-Contagem','Rua Verao','Rua Verão'),
('BR-MG-Contagem','Rua Vereador Antonio Faria','Rua Vereador Antônio Faria'),
('BR-MG-Contagem','Rua Vereador Goncalo Braz de Matto','Rua Vereador Gonçalo Braz de Matto'),
('BR-MG-Contagem','Rua Vereador Joao Cota','Rua Vereador João Cota'),
('BR-MG-Contagem','Rua Vereador Jose Augusto Dini','Rua Vereador José Augusto Dini'),
('BR-MG-Contagem','Rua Vereador Jose Pimenta','Rua Vereador José Pimenta'),
('BR-MG-Contagem','Rua Via Lactea','Rua Via Láctea'),
('BR-MG-Contagem','Rua Vicentino Jose Herculano','Rua Vicentino José Herculano'),
('BR-MG-Contagem','Rua Vinhatico','Rua Vinhático'),
('BR-MG-Contagem','Rua Vinicius de Morais','Rua Vinícius de Morais'),
('BR-MG-Contagem','Rua Vinte e Tres','Rua Vinte e Três'),
('BR-MG-Contagem','Rua Virgilio Cesar','Rua Virgílio César'),
('BR-MG-Contagem','Rua Virgilio Melo Franco','Rua Virgílio Melo Franco'),
('BR-MG-Contagem','Rua Visconde Itaborai','Rua Visconde Itaboraí'),
('BR-MG-Contagem','Rua Visconde Sabara','Rua Visconde Sabará'),
('BR-MG-Contagem','Rua Visconde de Itaborai','Rua Visconde de Itaboraí'),
('BR-MG-Contagem','Rua Visconde de Saboia','Rua Visconde de Sabóia'),
('BR-MG-Contagem','Rua Vitor Diniz Moreira','Rua Vítor Diniz Moreira'),
('BR-MG-Contagem','Rua Vitoria','Rua Vitória'),
('BR-MG-Contagem','Rua Wagner Magalhaes Labadie','Rua Wagner Magalhães Labadie'),
('BR-MG-Contagem','Rua Wilson Jose de Souza Bical','Rua Wilson José de Souza Bical'),
('BR-MG-Contagem','Rua Zamiro Nelson de Souza','Rua Zamiro Nélson de Souza'),
('BR-MG-Contagem','Rua Ze de Jove','Rua Zé de Jove'),
('BR-MG-Contagem','Rua Zeze Camargos','Rua Zezé Camargos'),
('BR-MG-Contagem','Rua da Africa','Rua da África'),
('BR-MG-Contagem','Rua da Asia','Rua da Ásia'),
('BR-MG-Contagem','Rua da Australia','Rua da Austrália'),
('BR-MG-Contagem','Rua da Belgica','Rua da Bélgica'),
('BR-MG-Contagem','Rua da Gloria','Rua da Glória'),
('BR-MG-Contagem','Rua da Grecia','Rua da Grécia'),
('BR-MG-Contagem','Rua da Italia','Rua da Itália'),
('BR-MG-Contagem','Rua da Siberia','Rua da Sibéria'),
('BR-MG-Contagem','Rua da Siria','Rua da Síria'),
('BR-MG-Contagem','Rua da Suecia','Rua da Suécia'),
('BR-MG-Contagem','Rua das Acacias','Rua das Acácias'),
('BR-MG-Contagem','Rua das Araucarias','Rua das Araucárias'),
('BR-MG-Contagem','Rua das Azaleias','Rua das Azaléias'),
('BR-MG-Contagem','Rua das Buganvilias','Rua das Buganvílias'),
('BR-MG-Contagem','Rua das Garcas','Rua das Garças'),
('BR-MG-Contagem','Rua das Hortensias','Rua das Hortênsias'),
('BR-MG-Contagem','Rua das Magnolias','Rua das Magnólias'),
('BR-MG-Contagem','Rua das Orquideas','Rua das Orquídeas'),
('BR-MG-Contagem','Rua das Vitorias-Regias','Rua das Vitórias-Régias'),
('BR-MG-Contagem','Rua do Arco-Iris','Rua do Arco-Íris'),
('BR-MG-Contagem','Rua do Imperio','Rua do Ímpério'),
('BR-MG-Contagem','Rua do Mexico','Rua do México'),
('BR-MG-Contagem','Rua do Pavao','Rua do Pavão'),
('BR-MG-Contagem','Rua do Petroleo','Rua do Petróleo'),
('BR-MG-Contagem','Rua do Quintao','Rua do Quintão'),
('BR-MG-Contagem','Rua do Sabia','Rua do Sabiá'),
('BR-MG-Contagem','Rua do Silencio','Rua do Silêncio'),
('BR-MG-Contagem','Rua dos Abricos','Rua dos Abricós'),
('BR-MG-Contagem','Rua dos Alamos','Rua dos Álamos'),
('BR-MG-Contagem','Rua dos Anturios','Rua dos Antúrios'),
('BR-MG-Contagem','Rua dos Assanhacos','Rua dos Assanhaços'),
('BR-MG-Contagem','Rua dos Canarios','Rua dos Canários'),
('BR-MG-Contagem','Rua dos Espanhois','Rua dos Espanhóis'),
('BR-MG-Contagem','Rua dos Expedicionarios','Rua dos Expedicionários'),
('BR-MG-Contagem','Rua dos Hungaros','Rua dos Húngaros'),
('BR-MG-Contagem','Rua dos Ingas','Rua dos Ingás'),
('BR-MG-Contagem','Rua dos Ipes','Rua dos Ipês'),
('BR-MG-Contagem','Rua dos Jacarandas','Rua dos Jacarandás'),
('BR-MG-Contagem','Rua dos Jatobas','Rua dos Jatobás'),
('BR-MG-Contagem','Rua dos Jequitibas','Rua dos Jequitibás'),
('BR-MG-Contagem','Rua dos Jesuitas','Rua dos Jesuítas'),
('BR-MG-Contagem','Rua dos Joao de Barros','Rua dos João de Barros'),
('BR-MG-Contagem','Rua dos Lirios','Rua dos Lírios'),
('BR-MG-Contagem','Rua dos Sabias','Rua dos Sabiás'),
('BR-MG-Contagem','Travessa C Tres','Travessa C Três'),
('BR-MG-Contagem','Travessa Tres','Travessa Três'),
('BR-MG-Contagem','Via Gastao Camargos','Via Gastão Camargos'),
('BR-MG-Contagem','Avenida Jk','Avenida JK'),
('BR-MG-Contagem','Avenida Pio Xii','Avenida Pio XII'),
('BR-MG-Contagem','Rodovia Br 040','Rodovia BR-040'),
('BR-MG-Contagem','Rodovia Br-040 Km 522/523','Rodovia BR-040 km 522/523'),
('BR-MG-Contagem','Rodovia Br-040 Km 688','Rodovia BR-040 km 688'),
('BR-MG-Contagem','Rua Curral Del Rei','Rua Curral del Rei'),
('BR-MG-Contagem','Rua Francisco Cassimiro D''Ávila','Rua Francisco Cassimiro d''Ávila'),
('BR-MG-Contagem','Rua Papa Paulo Vi','Rua Papa Paulo VI'),
('BR-MG-Contagem','Rua Pedro Henrique Trindade Da','Rua Pedro Henrique Trindade da'),
('BR-MG-Contagem','Rua Pio Xii','Rua Pio XII'),
('BR-MG-Contagem','Rua Rio D''Ouro','Rua Rio d''Ouro'),
('BR-MG-Contagem','Avenida Doutor Joao Augusto Fonseca E','Avenida Doutor João Augusto Fonseca e'),
('BR-MG-Contagem','Avenida J0hann Sadra','Avenida Johann Sadra'),
('BR-MG-Contagem','Avenida Princeza Izabel','Avenida Princesa Izabel'),
('BR-MG-Contagem','Praça Doutor Doutor Alvaro Camargos','Praça Doutor Álvaro Camargos'),
('BR-MG-Contagem','Praça Princeza Isabel','Praça Princesa Isabel'),
('BR-MG-Contagem','Rua Agenor Lopes Cancado','Rua Agenor Lopes Cansado'),
('BR-MG-Contagem','Rua Alemanha','Rua da Alemanha'),
('BR-MG-Contagem','Rua Antonio A. Da Costa','Rua Antônio A. da Costa'),
('BR-MG-Contagem','Rua Basilea','Rua Basileia'),
('BR-MG-Contagem','Rua Capitao Antonio Joaquim Da','Rua Capitão Antônio Joaquim da'),
('BR-MG-Contagem','Rua Coronel Americo T. Guimaraes','Rua Coronel Américo Teixeira Guimarães'),
('BR-MG-Contagem','Rua Coronel Francisco A. Pereira','Rua Coronel Francisco Antônio Pereira'),
('BR-MG-Contagem','Rua Coronel Joao M. Azevedo','Rua Coronel João Mendonça Azevedo'),
('BR-MG-Contagem','Rua Coronel Jose B. Oliveira','Rua Coronel José Bernardo Oliveira'),
('BR-MG-Contagem','Rua Coronel Jose Pedro A. Lima','Rua Coronel José Pedro de Araújo Lima'),
('BR-MG-Contagem','Rua Crisopracio','Rua Crisopásio'),
('BR-MG-Contagem','Rua Cristiano F. T. Guimaraes','Rua Cristiano Franca Teixeira Guimarães'),
('BR-MG-Contagem','Rua Deputado Lourenco F. De Andrade','Rua Deputado Lourenço Ferreira de Andrade'),
('BR-MG-Contagem','Rua Diacono Alair Henrique De','Rua Diácono Alair Henrique de'),
('BR-MG-Contagem','Rua Dom Manoel C. Nunes','Rua Dom Manoel Coelho Nunes'),
('BR-MG-Contagem','Rua Dorinato Lima','Avenida Dorinato Lima'),
('BR-MG-Contagem','Rua Doutor Doutor Aguiar Pessoa','Rua Doutor Aguiar Pessoa'),
('BR-MG-Contagem','Rua Doutor Doutor Antonio Aleixo','Rua Doutor Antônio Aleixo'),
('BR-MG-Contagem','Rua Doutor Doutor Antonio de C. Lage','Rua Doutor Antônio de Carvalho Lage'),
('BR-MG-Contagem','Rua Doutor Doutor Artur Hermeto','Rua Doutor Artur Hermeto'),
('BR-MG-Contagem','Rua Doutor Doutor Belmiro Medeiros','Rua Doutor Belmiro Medeiros'),
('BR-MG-Contagem','Rua Doutor Doutor Bernardo Monteiro','Rua Doutor Bernardo Monteiro'),
('BR-MG-Contagem','Rua Doutor Doutor Cicero de Castro','Rua Doutor Cícero de Castro'),
('BR-MG-Contagem','Rua Doutor Doutor Coelho de Moura','Rua Doutor Coelho de Moura'),
('BR-MG-Contagem','Rua Doutor Doutor Edson Diniz','Rua Doutor Edson Diniz'),
('BR-MG-Contagem','Rua Doutor Doutor Floriano Lemos','Rua Doutor Floriano Lemos'),
('BR-MG-Contagem','Rua Doutor Doutor Jose Antero Monteiro','Rua Doutor José Antero Monteiro'),
('BR-MG-Contagem','Rua Doutor Doutor Juju','Rua Doutor Juju'),
('BR-MG-Contagem','Rua Doutor Doutor Julio Ribeiro','Rua Doutor Júlio Ribeiro'),
('BR-MG-Contagem','Rua Doutor Doutor Louis Ensch','Rua Doutor Louis Ensch'),
('BR-MG-Contagem','Rua Doutor Doutor Luiz','Rua Doutor Luiz'),
('BR-MG-Contagem','Rua Doutor Doutor Mariano de Oliveira','Rua Doutor Mariano de Oliveira'),
('BR-MG-Contagem','Rua Doutor Doutor Mario Guerra','Rua Doutor Mário Guerra'),
('BR-MG-Contagem','Rua Doutor Doutor Nabor Campos','Rua Doutor Nabor Campos'),
('BR-MG-Contagem','Rua Doutor Doutor Olegario Ribeiro','Rua Doutor Olegário Ribeiro'),
('BR-MG-Contagem','Rua Doutor Doutor Otavio Avelar','Rua Doutor Otávio Avelar'),
('BR-MG-Contagem','Rua Doutor Doutor Tacito Guimaraes','Rua Doutor Tacito Guimarães'),
('BR-MG-Contagem','Rua Doutor Doutor Vicente Salles Dias','Rua Doutor Vicente Salles Dias'),
('BR-MG-Contagem','Rua Felisberta F. De Carvalho','Rua Felisberta Francisca de Carvalho'),
('BR-MG-Contagem','Rua Francisco D. Castanheira','Rua Francisco Durães Castanheiras'),
('BR-MG-Contagem','Rua Francisco R. Pereira','Rua Francisco Rodrigues Pereira'),
('BR-MG-Contagem','Rua Inglaterra','Rua da Inglaterra'),
('BR-MG-Contagem','Rua Joao Xxiii','Rua João XXIII'),
('BR-MG-Contagem','Rua Jose Americo Cancado Bahia','Rua José Américo Cansado Bahia'),
('BR-MG-Contagem','Rua Marcelino Teonilo Gomes','Rua Marcelino Teonílio Gomes'),
('BR-MG-Contagem','Rua Maria Rita D. Souza','Rua Maria Rita Diniz e Souza'),
('BR-MG-Contagem','Rua Maria da Conceicao','Rua Maria da Conceição de São José'),
('BR-MG-Contagem','Rua Maria da Conceicao de Sao','Rua Maria da Conceição de São José'),
('BR-MG-Contagem','Rua Marquez de Parana','Rua Marquês de Paraná'),
('BR-MG-Contagem','Rua Mopaje','Rua Mopagé'),
('BR-MG-Contagem','Rua Odecio Vicente da Silva','Rua Odésio Vicente da Silva'),
('BR-MG-Contagem','Rua Olhos D''Água','Rua Olhos d''Água'),
('BR-MG-Contagem','Rua Oscavo de F. Lobato','Rua Oscavo Lobato'),
('BR-MG-Contagem','Rua Padre Lopes Cancado','Rua Padre Lopes Cansado'),
('BR-MG-Contagem','Rua Paulo D. Assuncao','Rua Paulo D''Assunção'),
('BR-MG-Contagem','Rua Princesa Izabel','Avenida Princesa Izabel'),
('BR-MG-Contagem','Rua Refinaria Alberto Pascoaline','Rua Refinaria Alberto Pasqualine'),
('BR-MG-Contagem','Rua Rua Sao Joao Del Rey','Rua Rua São João del Rey'),
('BR-MG-Contagem','Rua Sao Joao Del Rei','Rua São João del Rey'),
('BR-MG-Contagem','Rua Theodoro M. Pires','Rua Teodoro Mendes Pires'),
('BR-MG-Contagem','Rua Turqueza','Rua Turquesa'),
('BR-MG-Contagem','Rua da Inglaterra','Rua Inglaterra'),
('BR-MG-Contagem','Rua da Suissa','Rua da Suiça'),
('BR-MG-Contagem','Rua de Atenas','Rua Atenas'),
('BR-MG-Contagem','Rua de Berlim','Rua Berlim'),
('BR-MG-Contagem','Rua de Berna','Rua Berna'),
('BR-MG-Contagem','Rua de Bruxelas','Rua Bruxelas'),
('BR-MG-Contagem','Rua de Constantinopla','Rua Constantinopla'),
('BR-MG-Contagem','Rua de Haia','Rua Haia'),
('BR-MG-Contagem','Rua de Lisboa','Rua Lisboa'),
('BR-MG-Contagem','Rua de Londres','Rua Londres'),
('BR-MG-Contagem','Rua de Moscou','Rua Moscou'),
('BR-MG-Contagem','Rua de Paris','Rua Paris'),
('BR-MG-Contagem','Rua de Roma','Rua Roma'),
('BR-MG-Contagem','Rua de Sofia','Rua Sofia'),
('BR-MG-Contagem','Rua de Viena','Rua Viena')

) AS t (isolabel_ext,old,new)
;
